### ISSUE TITLE
Bugs in Pisi

### ISSUE THREAD

**Issue by WetGeek** [pisilinux/main#10084]
I'm a Solus user from the US, and taking a look at Pisi upon a recommendation from a friend.  Using the beta has been fairly uneventful so far, but I have encountered a few surprises.

I modified /etc/fstab to support the nfs shares from my NAS, and added mount points to /mnt, but was unable to mount the shares.  I could find neither nfs-utils nor nfs-common in the repository.  I installed libnfs, but that did not enable me to mount these shares.

I've installed Vivaldi as the default browser, but when I tried to access this location, it was Firefox that was used instead.  I needed to load the Lastpass extension into Firefox in order to log on to my Github account.

Otherwise, Pisi is looking very good!  I hope these are just beta issues that will be resolved soon.

**Comment by suvari** [comment]
Thank for info, fixed.
