### ISSUE TITLE
ntfs is not being recognized for usb disks when it is plugged

### ISSUE THREAD

**Issue by saygili** [pisilinux/main#1073]
Hello,
When I plug usb disk to my computer, it tries to mount automatically as expected, but not able to succeed since ntfs filesystem is not supported.
Instead, if I manually mount it with ntfs-3g chosen, it works as below:
Not working:
sudo mount -t ntfs -o uhelper=udisks2,nodev,nosuid,uid=1000,gid=100 /dev/sdb1 /media/mountpoint
Working:
sudo mount -t ntfs-3g -o uhelper=udisks2,nodev,nosuid,uid=1000,gid=100 /dev/sdb1 /media/mountpoint

Would you please update udev so that it automatically tries supported filesystem which is ntfs-3g.
BR
Murat

**Comment by ertugerata** [comment]
@saygili udev update derken ?

**Comment by saygili** [comment]
Merhaba,

Şunu demek istedim: Diski taktığımızda ntfs yerine ntfs-3g şeklinde mount etmesi gerekiyor scriptlerin. Bu automount işini yapan anlamında belirtmek istedim.
Selamlar,

Murat

**Comment by ertugerata** [comment]
tek bu işi yapan bir udev rules bakmak lazım. bir tane buldum. çakıştı sanırım

**Comment by saygili** [comment]
Bence ntfs olanı ntfs-3g ile değiştirebilseniz yeterli olur diye düşünüyorum.

**Comment by ertugerata** [comment]
fixed. in commit https://github.com/pisilinux/main/commit/e645c41918273809e32e9ce2553fffabd0a56edb
