### ISSUE TITLE
Virtualbox Fails

### ISSUE THREAD

**Issue by saygili** [pisilinux/main#1088]
saygili@kizilyildiz ~ $ sudo pisi it virtualbox
Total size of package(s): 15.77 MB
Downloading 1 / 1
Package virtualbox found in repository pisi
virtualbox-5.0.12-20-p01-x86_64.pisi (15.8 MB)100%      1.78 MB/s [00:00:01] [complete]
Installing 1 / 1
virtualbox-5.0.12-20-p01-x86_64.pisi [cached]
Installing virtualbox, version 5.0.12, release 20
Extracting the files of virtualbox
Configuring virtualbox package
virtualbox configuration failed.
Installed virtualbox
saygili@kizilyildiz ~ $

**Comment by ertugerata** [comment]
virtualbox without-gui ilgi istiyor. package.py de bir dosyanın izinlerinin değişmesi gerekiyor ama o dosya orada yok.

**Comment by ertugerata** [comment]
qt5 li virrtualbox depoda.
