### ISSUE TITLE
PisiLinux 2.0 Alfa7 Installation boot gives unable to handle kernel paging request

### ISSUE THREAD

**Issue by saygili** [pisilinux/main#1089]
During boot for installation after choosing language and boot, it gives unable to handle kernel paging request.

**Comment by ertugerata** [comment]
same issue https://github.com/pisilinux/core/issues/47 ?

**Comment by saygili** [comment]
![dsc_0044](https://cloud.githubusercontent.com/assets/16668304/12384546/c8901432-bdbb-11e5-9e99-fc1bcebed351.JPG)

**Comment by ertugerata** [comment]
nouveau problem e benziyor. blacklist ekleyip boot etmeyi dener misin

**Comment by saygili** [comment]
Problem cd den boot edip kurulum dilini seçtikten sonra tekrar oluyor. Kurulum sonrası değil yani.

**Comment by saygili** [comment]
Problem cd den boot edip kurulum dilini seçtikten sonra oluyor. Kurulum sonrası değil yan

**Comment by ertugerata** [comment]
iso ile boot ederken kernel satırına 
rdblacklist=nouveau nomodeset 

ekleyip açılıp açılmadığına bakabilir misiniz?

**Comment by saygili** [comment]
boot sonrası simsiyah ekran geliyor. O parametreler ile açmıyor.

**Comment by saygili** [comment]
Ekteki ekranı geçmek için ne yapmak lazım? Modprobe: error: could not insert 'nvidia' : no such device
![dsc_0091](https://cloud.githubusercontent.com/assets/16668304/13601029/acdd5e38-e535-11e5-8f94-871bf17e969d.JPG)

**Comment by alihanozturk** [comment]
açılışta kernel satırına "blacklist=nvidia" yazıp denermisiniz

**Comment by saygili** [comment]
Alihan Bey Merhaba,
4 Mart'ta gelen güncellemeler tüm sistemi çökertti. Söylediğinizi daha sonra deneyip dönüş yapacağım. Ama 4 Marttaki kernel ve diğer güncellemeleri kontrol edebilir misiniz? Çok büyük sorunlar var o bundle içerisinde.
Selamlar,

Murat

**Comment by saygili** [comment]
Merhaba,

Maalesef aynı sonuç.
Murat

**Comment by ertugerata** [comment]
öneriler ile yeni iso larla deneyipbilgilendirme yapabilir misiniz?

**Comment by ertugerata** [comment]
Cevap olmadığı için kapatıldı
