### ISSUE TITLE
crystalhd-firmware linux-firmware in içinde mevcut. 

### ISSUE THREAD

**Issue by ertugerata** [pisilinux/main#1097]
vlc derlenme bağımlılığı olan crystalhd-firmware linux-firmware içinde var. Kontrol edilmesi gerek. 

pisi info crystalhd-firmware -f
/lib/firmware/bcm70012fw.bin, type: data, size: 2786404, sha1sum: 29e3f754df46a72f9a979dad504b53e9f29667e4
/lib/firmware/bcm70015fw.bin, type: data, size: 864276, sha1sum: 64b0f7016c000b472ed14d0282a918ed558d842f
Paket pisi deposunda bulundu:

pisi info linux-firmware -f |grep crystalhd
/lib/firmware/crystalhd/BOM, type: data, size: 211, sha1sum: afb839bdb1969e7bc0672b48cc88c8f6ab5c6d6d
/lib/firmware/crystalhd/bcm70012fw.bin, type: data, size: 2786404, sha1sum: c1bd3b60af5365de5ee5214b24a5fd3d3c600322
/lib/firmware/crystalhd/bcm70015fw.bin, type: data, size: 868372, sha1sum: 247c96bdd497d4dd5b584a974df05ee89468a301

**Comment by aydemir** [comment]
<pre><code class="python">
    print("Merhaba Dünya!")
    </code></pre>

**Comment by aydemir** [comment]
def foo():
    if not bar:
        return True
