### ISSUE TITLE
ffmpeg de güvenlik açığı

### ISSUE THREAD

**Issue by bferturk** [pisilinux/main#1172]
2.8.4 öncesi tüm sürümler etkilenmiş.

https://bugs.archlinux.org/task/47738

--disable-network 
seçeneği ile yeniden inşa edilmeli

mümkünse 1.2 içinde yapılsın.

**Comment by ayhanyalcinsoy** [comment]
Teşşürler Burak

**Comment by ertugerata** [comment]
https://github.com/pisilinux/main/commit/f85800bbd373cf407eed36d6c76c5d0654470e7e ile 2.8.6 sürüme geçildi.

**Comment by bferturk** [comment]
Ne demek @ayhanyalcinsoy .Kolaylıklar dilerim.
