### ISSUE TITLE
sddm numlock

### ISSUE THREAD

**Issue by alihanozturk** [pisilinux/main#1174]
Files olarak eklenen sddm.conf dosyasında bulunan sddm başlangıcında Numlock=none yazan satırı Numlock=on şeklinde değiştirmek son kullanıcı içinde yararlı olacaktır :) her sddm açılışında numlock a basmak gereksiz :)

**Comment by bferturk** [comment]
bazı klavyelerde numpad tuşları olmadığı için varsayılan olarak numlock açık gelmesi sakıncalı olabilir.

**Comment by ertugerata** [comment]
ne oldu bu issue ? @alihanozturk

**Comment by alihanozturk** [comment]
Karar vermemiz gerekli. Bana göre sddm.conf ta Numlock=on bu düzenlemeyi yapmalıyız.

**Comment by onlined** [comment]
Varsayılan olarak kapalı gelmesi ve bu ayarın değiştirilebilmesi en temizi bence.

**Comment by alihanozturk** [comment]
Bu ayarın değişitirilmesi son kullanıcı için zor. Masaüstüne yükleyen kullanıcılarımız var. Klavyenin numlock tuşunun açık gelmesinin bir zararının olacağını sanmıyorum.

**Comment by onlined** [comment]
Kaptana bu ayarı koymak da düşünülebilir. Böylece ilk açılışta bu ayar belirlenmiş olur.

**Comment by ertugerata** [comment]
@onlined +1
