### ISSUE TITLE
IcedTea-web

### ISSUE THREAD

**Issue by saygili** [pisilinux/main#1175]
Hi,

Is it possible to have IcedTea-web in repo?

http://icedtea.wildebeest.org/download/source/icedtea-web-1.6.2.tar.gz

BR
Murat

**Comment by saygili** [comment]
I have tried to compile by myself but it asks firefox-devel also which is not in repository.

**Comment by alihanozturk** [comment]
iced-tea-web7 depoya alınmıştır. Kayıt kapanabilir.
