### ISSUE TITLE
pangox-compat is missing in repo

### ISSUE THREAD

**Issue by saygili** [pisilinux/main#1182]
Hello,
The libraries such as pangox-compat existing in 1.2 is missing in 2.0.

BR

Murat

**Comment by ertugerata** [comment]
şu ana kadar bağımlılık nedeniyle pangox-compat'a gerek olmadı. contrib depoya bağımlılıklarını ayarlayarak alabilirsiniz.

**Comment by saygili** [comment]
Pisi 1.2 de var ve cisco vpn Client için lazım. Neden lazım olan programları çıkarıyorsunuz. Gerek olmadı derken kime gereksiz anlamadım.  Çok saçma.

**Comment by ertugerata** [comment]
paketi üzerine alırsın, docker den geçirirsin, contrib depo için pr istersin. çok gereken bir şey olduğunu kabul ettirirsin, main depoya alınır, farm da derlenir, depoya girer, derlenmez ise contrib e oradan da /dev/null e geri döner.

**Comment by saygili** [comment]
Çok güzel bir yaklaşım sizi tebrik ederim. Thanks for your nice approach. Congragulations.

**Comment by saygili** [comment]
Bilgisayarına her program kuranın paket geliştirmesi veya program yazması gerekiyor değil mi?

**Comment by ertugerata** [comment]
yoo ama issue girenin de ne yapmak istediğini niyet okuma ile de bilemiyoruz sonuçta.

**Comment by saygili** [comment]
Daha önceden depoya koyarken kimin niyeti ile koymuştunuz? O zaman okudunuz, sonra kullanan arkadaş öldü o yüzden de depodan mı çıkardınız?

**Comment by ertugerata** [comment]
1.2 main, core ve contrib için kurallar belirlendi. 2.0 nin 1.2 den çok farklı olduğunu belirtiyoruz, main ve core nin readme lerine bakabilirsin. 
paket bakıcısı olmak çok zor, hele ki gonullu yürütülen bir çalışmada. "Bakamayacağımız paketi almayalım" gibi basit bir düşünce içerisindeyiz. kişi başına 300 paket ile bakıcılık olmaz makulu 5o civarında olmalı. 
el atan birileri olur ise daha çok paket depolarda yer alabilir. ama şimdilik durum budur.
