### ISSUE TITLE
gconf is missing in repo.

### ISSUE THREAD

**Issue by saygili** [pisilinux/main#1183]

**Comment by ertugerata** [comment]
şu ana kadar bağımlılık nedeniyle gconf'a gerek olmadı. Gnome desktop gereksinimi olan gconf'u depoya almadık. https://github.com/pisilinux/PisiLinux/tree/master/main/desktop/gnome/base/gconf burada var. contrib depoya bağımlılıklarını ayarlayarak alabilirsiniz.

**Comment by saygili** [comment]
Gconf olmadan messenger çalışmıyor. Pisi 1.2 de olanı neden çıkarttınız. Çok anlamsız.

**Comment by ertugerata** [comment]
Messenger ?

**Comment by saygili** [comment]
http://messengerfordesktop.com/
