### ISSUE TITLE
Authorization Check Failed: Invalid Dbus Proxy

### ISSUE THREAD

**Issue by saygili** [pisilinux/main#1228]
Merhaba,

Son güncellemeler ile birlikte yetkilendirmelerde bir sorun oluştu. Kablosuz ağlara bağlanmaya çalıştığımda Authorization Check Failed: Invalid Dbus Proxy hatası alıyorum.

Bir de başlangıç menüsünden reboot/shutdown vs yetkileri kayboldu. Ekte ekran görüntülerini gönderiyorum.

Murat
![screenshot_20160308_174919](https://cloud.githubusercontent.com/assets/16668304/13607014/054d7afa-e557-11e5-9739-d4b1cde7c546.png)
![screenshot_20160308_174947](https://cloud.githubusercontent.com/assets/16668304/13607015/054f828c-e557-11e5-827d-815a3b2cc63f.png)

**Comment by ertugerata** [comment]
2.0 deposundan guncelleme yapilmamasi yonunde bir uyarimiz var. Yedek depoya gecmeniz gerek.

**Comment by saygili** [comment]
2.0 Alpha 7 kullanıyorum. Buna rağmen mi?

**Comment by ertugerata** [comment]
Kanal da sorsaydiniz keske. Toolchain gecisi bir cok paketi kirdi.

**Comment by saygili** [comment]
Nereden bağlanabilirim kanala sizi yormayan?

**Comment by saygili** [comment]
Yormayayım.

**Comment by ertugerata** [comment]
pisi.slack.com a gelebilirsiniz

**Comment by ertugerata** [comment]
spidermonkey rebuild i polkit'te probem meydana getirmiş, polkit yeniden derlendi. bende problem yok. çözüm için başka bilgisayardan yeni polkit ve spidermonkey i indirip o bilgisayara taşıyıp yeniden kurmanız gerekmekte.

**Comment by saygili** [comment]
Çok teşekkür ederim sağolun.
