### ISSUE TITLE
yazıcı yönetimi

### ISSUE THREAD

**Issue by erkanisik1** [pisilinux/main#1236]
başlat -> sistem -> yazıcıları yönet dediğimde 
KDEInit 'htmlview' uygulamasını başlatamadı:
'/usr//usr/lib/libkdeinit5_htmlview' kitaplığı açılamadı.
Cannot load library /usr//usr/lib/libkdeinit5_htmlview: (/usr//usr/lib/libkdeinit5_htmlview.so: paylaşımlı nesne dosyası açılamıyor: Böyle bir dosya ya da dizin yok) hatası veriyor

**Comment by ertugerata** [comment]
bunu deneyebilmek için ne lazım ?

**Comment by erkanisik1** [comment]
yazıcımı tanıtmak istediğimde bu hatayı veriyordu yazıcımda samsung scx 3405fw, samsungun kendi linux sürücüsü mevcut direk kuruluyor, kurulum yapıldıktan sonra yazıcıları yönet dediğimde bu hatayı vermişti.

**Comment by alihanozturk** [comment]
Bu hatanın durumu nedir acaba. Şu anda yazıcılarla ilgili bir sorun kalmadı.
