### ISSUE TITLE
dos2unix

### ISSUE THREAD

**Issue by saygili** [pisilinux/main#1237]
Merhaba,
dos2unix paketine ait olan dos2unix ve hd2u depoda mevcut. 

http://ciftlik.pisilinux.org/pisi-2.0/h/hd2u/

Ama sudo pisi it hd2u dediğinizde:
saygili@kizilyildiz ~ $ sudo pisi it hd2u
System error. Program terminated.
Repo item hd2u not found
Please use 'pisi help' for general help.

Hatası geliyor. Acaba indexlemede bir sorun mu var?
saygili@kizilyildiz ~ $ pisi la |grep -i hd2u
saygili@kizilyildiz ~ $

Selamlar,

Murat

**Comment by ertugerata** [comment]
thanks. index işlemi için obsolete edilmiş gözüküyor.

**Comment by saygili** [comment]
bu dosya olmadan dos2unix çalışmıyor.

**Comment by ertugerata** [comment]
Yeniden kurmayi dener misiniz.

**Comment by saygili** [comment]
Sonuç yine aynı. Bir de son updateler ile gelen libpng firefoxun çalışmasını engelliyor.

**Comment by ertugerata** [comment]
O konu son libpng rebuild i ile cozuldu

**Comment by ertugerata** [comment]
pisi up -dsy ile gunceller misiniz

**Comment by saygili** [comment]
Denedim updatler yüklendi ama sonuç yine aynı.

aygili@kizilyildiz ~ $ sudo pisi it hd2u
System error. Program terminated.
Repo item hd2u not found
Please use 'pisi help' for general help.
Use --debug to see a traceback.

**Comment by ertugerata** [comment]
hd2u paketi artik yok. Dos2unix icerisine alindi. Dos2unix i tekrar yukleyiniz demek istemistim. Pardon

**Comment by saygili** [comment]
Tamam düzelmiş. Elinize sağlık.
