### ISSUE TITLE
foomatic-db

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#1328]
Başarısız
Could not fetch destination file "http://source.pisilinux.org/1.0/foomatic-db-4.0-20160323.tar.gz": [Errno 14] HTTP Error 404 - Not Found
http://ciftlik.pisilinux.org/ciftlik/compiledetail/6427
foomatic-db-nonfree Başarısız Build dependency foomatic-db cannot be satisfied

**Comment by ertugerata** [comment]
build OK
