### ISSUE TITLE
ppp

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#1346]
Başarısız
Could not fetch destination file "http://source.pisilinux.org/1.0/ppp-dhcpc.tgz": [Errno 14] HTTP Error 404 - Not Found
http://ciftlik.pisilinux.org/ciftlik/compiledetail/5893

**Comment by alick01** [comment]
Aynı hata
http://ciftlik.pisilinux.org/ciftlik/compiledetail/6611

**Comment by ertugerata** [comment]
build OK
