### ISSUE TITLE
dejavu-fonts

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#1348]
Başarısız
[01;33mFetching source from mirror: http://heanet.dl.sourceforge.net/dejavu/dejavu-fonts-2.34.tar.bz2
[0m[01;33m*** 0 error(s), 1 warning(s)
[0m[01;31mProgram terminated.
[0m[01;31munpack: check_file_hash failed
http://ciftlik.pisilinux.org/ciftlik/compiledetail/5213

**Comment by ertugerata** [comment]
builded...
