### ISSUE TITLE
efivar

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#1351]
Başarısız
makeguids: malloc.c:2395: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
make[1]: *** Deleting file 'efivar-guids.h'
makeguids: malloc.c:2395: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
make[1]: *** Deleting file 'efivar-guids.h'
make[1]: *** No rule to make target 'efivar-guids.h', needed by 'efivar.h'.  Stop.
make: *** [src] Error 2
[01;31mProgram terminated.
[0m[01;31mCommand "make -j5 libdir=/usr/lib bindir=/usr/bin" failed, return value was 2.
[0m
http://ciftlik.pisilinux.org/ciftlik/compiledetail/6182

**Comment by ertugerata** [comment]
build OK
