### ISSUE TITLE
kdeclarative

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#1358]

**Comment by alick01** [comment]
Hata kaydı yok id 6520

**Comment by ertugerata** [comment]
build ok

**Comment by alick01** [comment]
Başarısız
System error. Program terminated. http://ciftlik.pisilinux.org/2.0-Beta/q/qt5-base/qt5-base-5.5.1-1-p2-x86_64.pisi
http://ciftlik.pisilinux.org/ciftlik/compiledetail/6827
