### ISSUE TITLE
kdepim

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#1361]
Başarısız
Build dependency qt5-webkit-devel cannot be satisfied
http://ciftlik.pisilinux.org/ciftlik/compiledetail/5283

**Comment by alick01** [comment]
AUTOGEN: error: process for /var/pisi/kdepim-15.12.3-1/work/kdepim-15.12.3/build/pimcommon/src/moc_autocorrectionwidget.cpp failed:
*** Error in `/usr/lib/qt5/bin/moc': free(): invalid next size (normal): 0x0000000001a992c0 ***
http://ciftlik.pisilinux.org/ciftlik/compiledetail/6727

**Comment by ertugerata** [comment]
build OK
