### ISSUE TITLE
kholidays

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#1372]
Başarısız
make[2]: *** [src/CMakeFiles/KF5Holidays.dir/sunriseset.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /var/pisi/kholidays-15.12.3-1/work/kholidays-15.12.3/src/holiday.cpp:26:0:
/var/pisi/kholidays-15.12.3-1/work/kholidays-15.12.3/src/holiday_p.h:646:16: warning: 'QString languageToCode(QLocale::Language)' defined but not used [-Wunused-function]
 static QString languageToCode(QLocale::Language language)
http://ciftlik.pisilinux.org/ciftlik/compiledetail/5290

**Comment by alick01** [comment]
/var/pisi/kholidays-15.12.3-1/work/kholidays-15.12.3/src/sunriseset.cpp: In function 'QTime KHolidays::SunRiseSet::utcSunrise(const QDate&, double, double)':
/var/pisi/kholidays-15.12.3-1/work/kholidays-15.12.3/src/sunriseset.cpp:183:20: error: 'isnan' was not declared in this scope
     if (isnan(delta))
http://ciftlik.pisilinux.org/ciftlik/compiledetail/6728

**Comment by ertugerata** [comment]
build OK
