### ISSUE TITLE
kmediaplayer

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#1375]
Başarısız
Build dependency qt5-base-devel cannot be satisfied
http://ciftlik.pisilinux.org/ciftlik/compiledetail/6581

**Comment by alick01** [comment]
Başarısız
Build dependency kparts-devel version >= 5.20.0 cannot be satisfied
http://ciftlik.pisilinux.org/ciftlik/compiledetail/6601

**Comment by ertugerata** [comment]
Build ok
