### ISSUE TITLE
Paket güncellerken hata

### ISSUE THREAD

**Issue by erdemoncel** [pisilinux/main#13972]
Pisi'yi ilk kurduktan sonra emacs kurmak istedik.

Ancak üzerinde pisi simgesi olan paket yöneticisi yerine üzerinde `Keşfet` yazan `yazılım merkezini` açmışız.

Bu hatayı verdi.

```
Error Type: <type 'exceptions.AttributeError'>
Error Value: pdb
  File : /usr/share/PackageKit/helpers/pisi/pisiBackend.py, line 631, in <module>
    main()
  File : /usr/share/PackageKit/helpers/pisi/pisiBackend.py, line 628, in main
    backend.dispatcher(sys.argv[1:])
  File : /usr/lib/python2.7/site-packages/packagekit/backend.py, line 740, in dispatcher
    self.dispatch_command(args[0], args[1:])
  File : /usr/lib/python2.7/site-packages/packagekit/backend.py, line 629, in dispatch_command
    self.get_updates(filters)
  File : /usr/share/PackageKit/helpers/pisi/pisiBackend.py, line 228, in get_updates
    pkg = self.packagedb.get_package(package)
  File : /usr/lib/pisilinux/pisi/db/packagedb.py, line 84, in get_package
    pkg, repo = self.get_package_repo(name, repo)
  File : /usr/lib/pisilinux/pisi/db/packagedb.py, line 157, in get_package_repo
    pkg, repo = self.pdb.get_item_repo(name, repo)
  File : /usr/lib/pisilinux/pisi/db/lazydb.py, line 120, in __getattr__
    raise AttributeError, attr

```

Pisi Linux'un küçük sürümünü Ventoy ile kurmayı denedik. Başarılı olmadı.

**Comment by alick01** [comment]
Önce sudo pisi ur komutunu verin sonra keşfeti açın ben öyle yaptım güncellemeyi

**Comment by erdemoncel** [comment]
Emacs kurulurken [xz açığından](https://archlinux.org/news/the-xz-package-has-been-backdoored/) acaba Pisi de etkilendi mi diye düşünmüştük.

Sonra emacs ve xterm'i açmayı denedik. Açmadı.

Bilgisayarı tekrar başlattık.

KDE oturum yöneticisi açıldı. Ama şifreyi kabul etmedi.

Uç birime düştük.

Uygulamaları çalıştırırken `libttfio.so.7 paylaşımlı nesne dosyası bulunamadı` diye bir hata aldık.

Uç birimden KDE başlamadı. Ancak fvwm başladı.

Firefox'u uç birimden başlatmayı denedik.

`XPCOM GlueLoad error for the /usr/lib/firefox/libmozgtk.so`

ve

`libttf.so can not open shared object` ve `couldn't load XPCOM` diye hatalar aldık.

En sonunda `sudo pisi upgrade` komutunu bir kaç kere vererek, bazı paketleri kaldırarak güncelleme başarılı oldu.

**Comment by erdemoncel** [comment]
Bahsettiğiniz gibi basit bir tazeleme hatası olabilir.

O zaman konuyu kapatalım.
