### ISSUE TITLE
libaccounts-glib

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#1409]
Başarısız
ag-account.c:2488:9: error: 'g_simple_async_report_error_in_idle' is deprecated: Use 'g_task_report_error' instead [-Werror=deprecated-declarations]
         g_simple_async_report_error_in_idle ((GObject *)account,
http://ciftlik.pisilinux.org/ciftlik/compiledetail/6073

**Comment by ertugerata** [comment]
build OK
