### ISSUE TITLE
okular

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#1437]
Başarısız
make[2]: *** [generators/poppler/CMakeFiles/okularGenerator_poppler.dir/generator_pdf.cpp.o] Error 1
make[1]: *** [generators/poppler/CMakeFiles/okularGenerator_poppler.dir/all] Error 2

http://ciftlik.pisilinux.org/ciftlik/compiledetail/5339

**Comment by ertugerata** [comment]
build OK
