### ISSUE TITLE
python-sphinx

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#1438]
Başarısız
ImportError: No module named markupsafe
[01;31mProgram terminated.
[0m[01;31mCommand "python -c "from sphinx.pycode.pgen2.driver import load_grammar ; load_grammar('/var/pisi/python-sphinx-1.3.1-1/install/usr/lib/python2.7/site-packages/sphinx/pycode/Grammar-py2.txt')"" failed, return value was 1.
http://ciftlik.pisilinux.org/ciftlik/compiledetail/6062

**Comment by ertugerata** [comment]
build OK
