### ISSUE TITLE
skey

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#1443]
Başarısız
Can't use 'defined(@array)' (Maybe you should just omit the defined()?) at ./fixpaths line 10.
make: *** [skey.1] Error 255
http://ciftlik.pisilinux.org/ciftlik/compiledetail/6216

**Comment by ertugerata** [comment]
openssh skey bağımlılığı lfs uyumluluğu gözetilerek kaldırıldı. skey contrib e doğru gidebilir
