### ISSUE TITLE
suspend

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#1445]
Başarısız
mkinitramfs configuration failed.
[0m[01;33mplymouth configuration failed.
[0mconfigure: WARNING: unrecognized options: --enable-plymouth
configure: WARNING: unrecognized options: --enable-plymouth
bootsplash.c:105:9: warning: 'bootsplash_write' is static but used in inline function 'bootsplash_progress' which is not static
  return bootsplash_write(buf);
http://ciftlik.pisilinux.org/ciftlik/compiledetail/5674

**Comment by ertugerata** [comment]
build Ok
