### ISSUE TITLE
kdbusaddons

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#1486]
Başarısız
Could not fetch destination file "http://ciftlik.pisilinux.org/2.0-Beta/q/qt5-base/qt5-base-5.5.1-1-p2-x86_64.pisi": [Errno 16] error setting timestamp on file /var/cache/pisi/packages/qt5-base-5.5.1-1-p2-x86_64.pisi.part from http://ciftlik.pisilinux.org/2.0-Beta/q/qt5-base/qt5-base-5.5.1-1-p2-x86_64.pisi, OSError: [Errno 2] No such file or directory: '/var/cache/pisi/packages/qt5-base-5.5.1-1-p2-x86_64.pisi.part'
http://ciftlik.pisilinux.org/ciftlik/compiledetail/6826

**Comment by ertugerata** [comment]
build OK
