### ISSUE TITLE
sistem font değişiminde hata

### ISSUE THREAD

**Issue by bferturk** [pisilinux/main#1554]
sistem fontu değiştirildiğinde yazılar karışıyor.

![screenshot_20160403_012959](https://cloud.githubusercontent.com/assets/16492796/14242919/24fd5f1e-fa5b-11e5-85c4-1801bc9da2ef.png)
![screenshot_20160403_013241](https://cloud.githubusercontent.com/assets/16492796/14242927/2baeaea8-fa5b-11e5-9fd4-7d76e8e10102.png)

**Comment by ertugerata** [comment]
noto-fonts a geçiş yaptığımda sorun yaşamadım. bir noto-fonts dener misin

**Comment by bferturk** [comment]
noto-sans yükleyince sistem otomatik geçti ama yazıtipi listesinde görünmedi.

![screenshot_20160403_115821](https://cloud.githubusercontent.com/assets/16492796/14243180/a4262af4-fa5c-11e5-8fbf-8bcd1ce7193a.png)
