### ISSUE TITLE
PyQt5 Kamerayı tanımıyor.

### ISSUE THREAD

**Issue by mthnzbk** [pisilinux/main#1567]
Qt ile webcam tanınabiliyorken pyqt5 modülü olan kamerayı görmüyor. QCameraInfo.availableCameras() gibi bir kod bağlı kameraları döndürmesi lazım.

**Comment by alihanozturk** [comment]
bu sorun çözülmüş olmalı live iso ile yapılan kurulumda son qt5 güncellemelerinden sonra kamera görünüyor.
