### ISSUE TITLE
Saat güncellemesi yapılamıyor.

### ISSUE THREAD

**Issue by saygili** [pisilinux/main#1580]
Sistem saati gui üzerinden değiştirilemiyor.
![screenshot_20160408_122006](https://cloud.githubusercontent.com/assets/16668304/14381139/a5e7124e-fd8c-11e5-88bc-aadd916e7506.png)

**Comment by ertugerata** [comment]
Bildirim icin tesekkurler. Hangi surum? 
System-settings
Kauth
Polkit-qt versiyonlarin neler ?

**Comment by alihanozturk** [comment]
Hatayı tekrarlıyormuyuz. Yoksa bu hatada düzeltildi sddm polkit dosyalarıyla.
