### ISSUE TITLE
libmtp; rules taşınması gerekli

### ISSUE THREAD

**Issue by alihanozturk** [pisilinux/main#1593]
libmtp paketi içerisinden çıkan;

69-libmtp.hwdb  dosyası ---> /etc/udev/hwdb.d altına alınmalı

69-libmtp.rules--->/etc/udev/rules.d  altına alınmalı

bizim sistemimizde with-udev neresidi? /usr/lib/udev mi yoks /lib/udev mi?

eğer /lib/udev ise rules, hwdb dosyaları ve mtp-probe dosyası(/usr/lib/udev altındalar) /lib/udev altına alınmalı.

**Comment by ertugerata** [comment]
docker in /etc/udev/rules altına koyduğumuz kuralı bir türlü çalışmıyordu. her seferinde plasma için bir hata meydana getiriyordu. onu  lib/udev/rules altına taşıdım o hata kalktı. 
bu mantık ile yaklaşıp rules leri** /lib/udev/rules.d** altına taşınmalı.

**Comment by alihanozturk** [comment]
o zman rules,hwdb ve mtp-probe dosyaları lib udev altına taşınsın abi. paketi güncelleyerek o işide halledelim.

**Comment by alihanozturk** [comment]
paket güncellenip rules gerekli yere alındı
