### ISSUE TITLE
plymounth başlamıyor

### ISSUE THREAD

**Issue by slarikan** [pisilinux/main#1653]
libply.so.4 arıyor

**Comment by ertugerata** [comment]
hata devam ediyor ama libply.so.4 arama hatası görünmüyor olmalı kontrol eder misiniz @slarikan

**Comment by slarikan** [comment]
Evet libply.so.4 aramıyor artık ama güzel bir başlama temasıda yok

**Comment by alihanozturk** [comment]
başlama teması var aslında ama paket kaynağı hatalı. 

Şu anda depo da mevcut olan plymouth 0.9.2 sürümü kaynak tarafından arızalı olduğu biliniyor. Bu yüzden plymouth un eski sürümü olan plymouth 0.8.8 sürümüne geri dönülmeli.

**Comment by ertugerata** [comment]
Plymount-0.8.8 e gecildi. Deneyip son durumu bildirebilir miniz?
