### ISSUE TITLE
Tercümelerin paketlerde güncellenesi

### ISSUE THREAD

**Issue by hkn1979** [pisilinux/main#1655]
Yeni dil Boşnakça, Özbekçe, Lezgice, Çuvaşça'nın dil paketlerinin eklenmesi ayrıcada Azericede güncellemeler olduğu için dil paketinin yenilenmesi gerekmektedir.

Lezgice'de başlangıç aşamasında ancak yinede bu dili koyabilirsiniz.

**Comment by hkn1979** [comment]
transifex te releasenotes.2-0 dosyası güncel mi acaba buna göre mi beta sürümü çıkacak?

**Comment by suvari** [comment]
desteklediğimiz diller: https://paste.kde.org/pjpidsphw

**Comment by hkn1979** [comment]
Mevcut KDE tercümeleri 

 <Translation language="ca_ES">
                <Translation language="pt_BR">
                <Translation language="it_IT">
                <Translation language="sv_SE">
                <Translation language="hu_HU">
                <Translation language="nl_NL">
                <Translation language="en_US">
                <Translation language="hr_HR">
                <Translation language="de_DE">
                <Translation language="pl_PL">
                <Translation language="es_ES">
                <Translation language="fr_FR">
                <Translation language="tr_TR">



benim takip ettiğim tercüme dosyalarından aşağıda bulunan dillerin paketlere girmesi uygun olacaktır. Ayrıca KDE dışı uygulamalarda da
göz ardı etmeyiniz.

EKLENMESİ UYGUN OLAN TERCÜME DOSYALARI			
			Bosnian(bs)
			Uzbek (uz) (şuan aktif tercümede kısa sürede %4 den %38 lere ulaştı.)
			Azerbaijani(az)
			Chuvash(cv) (varsa lütfen ekleyin)

//			ama ayrıca belirteyim, tranifex de ayrıca tercümesi yapılmış ancak sizin paketlemeye girmemiş dillerde olabilir.
