### ISSUE TITLE
qt5 bağımlısı bazı paketlerin derlenmesi

### ISSUE THREAD

**Issue by alihanozturk** [pisilinux/main#1670]
main/network/chat/telepathy-logger-qt/
main/network/chat/telepathy-qt5/
main/multimedia/sound/knowthelist/
 main/multimedia/video/vokoscreen/
 main/office/misc/qpdfview/
main/util/admin/pisido/
main/programming/library/signon/
main/programming/library/libaccounts-qt5/
main/desktop/toolkit/qtcreator/
main/desktop/kde/phonon/qt5-phonon/
main/desktop/toolkit/qscintilla2/
main/multimedia/video/smtube/
main/programming/language/python/pyqtermwidget5/
main/programming/misc/grantlee-qt5/
main/desktop/kde/phonon/qt5-phonon-backend-gstreamer/
main/desktop/kde/phonon/qt5-phonon-backend-vlc/
main/multimedia/graphics/librecad/
main/util/crypt/qca2-qt5/
main/desktop/kde/addon/prison-qt5/

signon-kwallet-extension, libsignon-glib

**Comment by ertugerata** [comment]
bu paketler yeniden derlendi mi?

**Comment by ertugerata** [comment]
@alihanozturk abi bunu tamamladıysak kapatalım mı?

**Comment by alihanozturk** [comment]
Kapatabiliriz. Tamamlandı bu liste.
