### ISSUE TITLE
ffmpeg eksik bağımlılık var

### ISSUE THREAD

**Issue by ertugerata** [pisilinux/main#169]
bağımlılıklara x265 ve libvpx eklenecek 

https://pisi.slack.com/files/ertugrul/F08A4K8BS/ffmpeg_checkelf.txt

**Comment by ertugerata** [comment]
@ayhanyalcinsoy ilgi gösterebilir misin abi

**Comment by ayhanyalcinsoy** [comment]
tamamlandı
