### ISSUE TITLE
Kulaklık sorunu

### ISSUE THREAD

**Issue by bferturk** [pisilinux/main#1827]
Sisteme sonradan takılan kulaklıktan ses gelmiyor. Yeniden başlatınca sorun yok.

**Comment by ertugerata** [comment]
same issue https://github.com/pisilinux/main/issues/2171 ?

**Comment by aydemir** [comment]
bir jak uygulaması depoya alalım

**Comment by ertugerata** [comment]
jack-connection-kit var idi sanırım?

**Comment by aydemir** [comment]
http://qjackctl.sourceforge.net/
http://www.jackaudio.org/

**Comment by bferturk** [comment]
#2171 ile aynı arıza bunu kapatalım diğeri açık kalsın.
