### ISSUE TITLE
init ekranı udevd hatası

### ISSUE THREAD

**Issue by alihanozturk** [pisilinux/main#1842]
Udevd[121]:Error running install comman for wl.

**Comment by alick01** [comment]
Eski bir makinem var onada kurayım dedim hp nx6325 aynı hatayı alıyorum kurulum çok uzun sürüyor ve programlar çok geç açılıyor. 3 Gb ram var ekran kartı ati amd x1150 wireless broadcom bcm 4312

**Comment by alihanozturk** [comment]
konsole açıp " su " komutu ile root yetkisi alıp aşağıdaki adımları uygulayınız.

1-) kate /etc/mkinitcpio.conf  açın
2-) MODULES="" satırını bulup MODULES="wl"  bu satırla değiştiriniz.
3-) kaydedip dosyayı kapatınız.
4-) mkinitcpio -p linux komutunu verip bilgisayarı yeniden başlatınız
