### ISSUE TITLE
Ayar dosyaları dizini değişmiş.

### ISSUE THREAD

**Issue by mthnzbk** [pisilinux/main#1869]
Önceden home altında .config5 de duran kde vs. ayarları pisilive ile kurulumda .config altına atılıyor. Bu yüzden Kaptan dosyaları bulamadığından hata veriyor.

**Comment by alihanozturk** [comment]
bu sorun çözüldü galiba. plasma-workspace paketinde kde-env.sh kapatıldığı için olmuştu bu hata. Kaptanda gerekli düzltme yapıldı.

[https://github.com/PisiLinuxNew/kaptan/commit/eccddc555b48157a8a75f11be4e9c47ce0e83983](url)

**Comment by mthnzbk** [comment]
Evet kaptanı .config e göre ayarladım.
