### ISSUE TITLE
kurulum

### ISSUE THREAD

**Issue by slarikan** [pisilinux/main#1870]
Beta live iso kurulumda hata verdi
Failled to unpack image/bootmnt/pisi/x86_64/desktop. sqfs
ve
rsync failed with error code 23.

**Comment by bferturk** [comment]
sha1sum yanlış olabilirmi ?

**Comment by slarikan** [comment]
sha1sum doğru usb ye yeniden yazdırdım kurulumda otomatik girişi işaretlemedim bu sefer kurulum tamamlandı.

**Comment by bferturk** [comment]
kapattım abi
