### ISSUE TITLE
sesde aygıt tercihi

### ISSUE THREAD

**Issue by slarikan** [pisilinux/main#1874]
Ekran kartım
01:00.0 VGA compatible controller: NVIDIA Corporation GT218 [GeForce 210] (rev a2)
01:00.1 Audio device: NVIDIA Corporation High Definition Audio Controller (rev a1)
bilgisayarı hdmi ile haparlörü olan monitöre bağlıyorum.
![screenshot_20160531_144939](https://cloud.githubusercontent.com/assets/1430827/15673590/6e2d0e84-2740-11e6-8c15-6dc381f49dc2.png)
Beta2 de ses ayarlarında aygıt tercihinde ses kartları görünmüyor ayarlama yapılamıyor. Beta da aylanabiliyordu.

**Comment by slarikan** [comment]
Arka Uç  da phonon gstreamer yokmuş bakalım kurayım dedim öyle bir paket yok.
Paket yöneticisinde phonon diye aradım ve bulduğu bütün paketleri kurdum.
Arka Uç da Phonon gstreamer ve phonon vlc geldi
Aygıt tercihi ne aygıt seçmede geldi.

**Comment by alihanozturk** [comment]
qt5-phonon-backend-gstreamer  bu paket isoda olmalı.

**Comment by ertugerata** [comment]
ses tamam ise hata kapatılabilir mi
