### ISSUE TITLE
hata kaydı

### ISSUE THREAD

**Issue by aligulle1** [pisilinux/main#1877]
acılışta eror no device specified for hibernation diyor 
desktop ve indirilenlerden başka dizin görunmuor udisk eksik

**Comment by ertugerata** [comment]
hangi iso?

**Comment by ertugerata** [comment]
hangi iso ve kurulum? 
grub.cfg de resume= 
karşılığı tanımlanmış mı

**Comment by ertugerata** [comment]
cevap yok ise hata giderilmiş mi oluyor ?

**Comment by aligulle1** [comment]
kusura bakma abi yeni gordum gıderılmıştı enson abi
