### ISSUE TITLE
bilgisayar donuyor

### ISSUE THREAD

**Issue by slarikan** [pisilinux/main#1895]
Herhangi bir şekilde (monitörü diğer birşeye bağlandığında, elektrikler gidip geldiğinde, Bilgisayar kesintisiz güç kaynağına takılı ama monitör takılı değil) Pisilinux 2.0 donuyor sadece fareyi gezdirebiliyorum oda tıklanmıyor.

**Comment by ertugerata** [comment]
hangi iso, dmesg vs çıktısı gerek.

**Comment by ertugerata** [comment]
Devam ediyor ise yeniden açılabilir. Eski sürüme ait bir hata mıdır ?
