### ISSUE TITLE
gönüllü bir türlü kurulamıyor

### ISSUE THREAD

**Issue by slarikan** [pisilinux/main#1936]
sudo pisi it docker pip3 python3-devel python3-setuptools
Unhandled internal exception.
Please file a bug report to <http://bugs.pardus.org.tr>.
<class 'pisi.graph.CycleException'>: Çember ile karşılaşıldı: ['perl-LWP-Protocol-https', 'perl-libwww'].

ve sudo pip3 install git+https://github.com/PisiLinuxNew/gonullu.git --upgrade sonrası
copying psutil/tests/__init__.py -> build/lib.linux-x86_64-3.4/psutil/tests
   running build_ext
   building 'psutil._psutil_linux' extension
   creating build/temp.linux-x86_64-3.4
   creating build/temp.linux-x86_64-3.4/psutil
   x86_64-pc-linux-gnu-gcc -pthread -Wno-unused-result -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -mtune=generic -march=x86-64 -O2 -pipe -fstack-protector -D_FORTIFY_SOURCE=2 -g -fPIC -fwrapv -fPIC -DPSUTIL_VERSION=420 -DPSUTIL_ETHTOOL_MISSING_TYPES=1 -I/usr/include/python3.4m -c psutil/_psutil_linux.c -o build/temp.linux-x86_64-3.4/psutil/_psutil_linux.o
   unable to execute 'x86_64-pc-linux-gnu-gcc': No such file or directory
   error: command 'x86_64-pc-linux-gnu-gcc' failed with exit status 1
   
   ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lu22u8mg/psutil/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-0i40zka5-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-lu22u8mg/psutil/

**Comment by ertugerata** [comment]
gcc kurulması gerekmiş, gonullu pisi olarak depoda mevcut. 
pisi it gonullu
komutyla kurabilirsiniz.
