### ISSUE TITLE
Yakuake Ayar Kayıt Sorunu

### ISSUE THREAD

**Issue by MuhammetDilmac** [pisilinux/main#1960]
Yakuake ekranına sağ tıklayıp geçerli profili düzenle deyip kaydettiğim font ayarları makinayı her yeniden başlatmamda gidiyor ve tekrar ayarları yapmam gerekiyor.

**Comment by ertugerata** [comment]
tekrarlanamadı.

**Comment by ertugerata** [comment]
Son durum nedir

**Comment by ertugerata** [comment]
bende çalışıyor.
