### ISSUE TITLE
ark arşiv listelemiyor.

### ISSUE THREAD

**Issue by mthnzbk** [pisilinux/main#1982]
Ark ile zip vs açtığımda içeriğini listelemiyor, ama unzip edebiliyor.

**Comment by ertugerata** [comment]
zip dosyası da oluşturmuyor

**Comment by aydemir** [comment]
konu bende

**Comment by poyraz76** [comment]
sorun ark arşiv aracında değil zip unzip paketlerinden kaynaklı gibi gözüküyor henüz sebebin ne olduğunu tespit edemedim.
