### ISSUE TITLE
Firefox kopyalama sorunu

### ISSUE THREAD

**Issue by Sam0bt** [pisilinux/main#2006]
Firefox'tan herhangi bir metni kopyaladıktan sonra kapattıldığında, kopya önbellekte kalmıyor. 
kde'nin kopyalama panosunu kullanmıyor sanırım.

**Comment by ertugerata** [comment]
bir şekilde debug için başka bilgiler gerek. önceden düzgün çalışıyordu hangi commit ten sonra değişti ?

**Comment by poyraz76** [comment]
firefox ile alakalı tüm sorunlar çözülmüştür.

**Comment by ertugerata** [comment]
hangi commit ile? depoya girdi mi
