### ISSUE TITLE
Beta 2 Sistem Kapatma Sorunu

### ISSUE THREAD

**Issue by prdsmehmetstc** [pisilinux/main#2013]
GUI'den kapat komutunu verdiğimde sddm'ye atıyor. Konsoldan kapatma emri verdiğimde ise hiç bir şey yapmıyor.

**Comment by ertugerata** [comment]
hata nın çözümlenebilmesi daha fazla bilgi gerekiyor. mesela daha önce problem yoktu şu programdan veya güncellemeden sonra oldu gibi

**Comment by prdsmehmetstc** [comment]
sıfır kurulum. Hiç bir işlem yapılmadı. sudo pisi up -dvsy yaptıktan sonra da aynı şekilde tabii. Ancak live'de bir problem yok.

**Comment by ertugerata** [comment]
hangi iso ?

**Comment by prdsmehmetstc** [comment]
Tüm Beta isolarında. Hepsinde denedim.

**Comment by ertugerata** [comment]
Devam ediyor mu

**Comment by ertugerata** [comment]
acpid paketi kapatmayı engelliyor sanki. paket kaldırıp dener misiniz?

**Comment by prdsmehmetstc** [comment]
prdsmehmetstc@pisi2beta: ~ $ dmesg | grep error
[    3.511650] iwlwifi 0000:02:00.0: Direct firmware load for iwlwifi-3160-17.ucode failed with error -2
[    4.502554] comar[570]: segfault at 7f078cabf0f0 ip 00007f078cabf0f0 sp 00007ffd9a7f1478 error 15
prdsmehmetstc@pisi2beta: ~ $ dmesg | grep failed
[    0.403327] pci 0000:03:00.0: BAR 6: failed to assign [mem size 0x00080000 pref]
[    3.511650] iwlwifi 0000:02:00.0: Direct firmware load for iwlwifi-3160-17.ucode failed with error -2
[    3.580567] ACPI Error: Method parse/execution failed [\_SB.PCI0.RP05.PEGP.DD02._BCL] (Node ffffa345868f1a78), AE_NOT_FOUND (20160422/psparse-542)
[   11.759793] ACPI: \_SB_.PCI0.RP05.PEGP: failed to evaluate _DSM
[   21.999480] ACPI: \_SB_.PCI0.RP05.PEGP: failed to evaluate _DSM
[   93.165062] ACPI: \_SB_.PCI0.RP05.PEGP: failed to evaluate _DSM
[ 3818.861509] ACPI: \_SB_.PCI0.RP05.PEGP: failed to evaluate _DSM
[ 3830.636706] ACPI: \_SB_.PCI0.RP05.PEGP: failed to evaluate _DSM
prdsmehmetstc@pisi2beta: ~ $

**Comment by prdsmehmetstc** [comment]
Benzer sorunları başka dağıtımlarda da yaşayanlar olmuş. İlgili linkler:

http://askubuntu.com/questions/462560/ubuntu-14-04-wont-shutdown-or-reboot

https://bugs.launchpad.net/ubuntu/+source/network-manager/+bug/869635

http://askubuntu.com/questions/87576/slow-shutdown-due-to-modemmanager-and-nm-dispatcher-action

**Comment by suvari** [comment]
Fixed
