### ISSUE TITLE
wine

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#2029]
wine kurdum.birlikte bağımlılık olarak sadece mpg123 cabextract ta kuruldu.atari 800 xl exe dosyasını kurmak istedim.
wine: error while loading shared libraries: libwine.so.1: cannot open shared object file: No such file or directory
Böyle hata verdi ancak,
pisi sf ile arattığımda wine paketi içinde usr/lib/libwine.so.1 dosyası var.

**Comment by alick01** [comment]
sudo pisi it wine-32bit dediğimde kurulacak paketlere baktım bunlar zaten wine psppec.xml de var ama wine ile kurulmadı.

**Comment by poyraz76** [comment]
Wine Hatalar düzeltildi.
