### ISSUE TITLE
paket kaldırılırken  "/usr/share/infodoes not exist on system..."  diye başlayan hata veriyor...

### ISSUE THREAD

**Issue by suvari** [pisilinux/main#2099]
Installed file /usr/share/info does not exist on system [Probably you manually deleted]...
gibi, uninstall sırasında hata veren paketler var.  (fontconfig alternatives icon-theme-hicolor libinput postgresql-server mesa-32bit e2fsprogs)

https://paste.kde.org/prytp6gp8

**Comment by ertugerata** [comment]
anlamadım bunu ?

**Comment by suvari** [comment]
Removing package fontconfig
Running pre removal operations for fontconfig
Installed file /var/cache/fontconfig does not exist on system [Probably you manually deleted]
Running post removal operations for fontconfig
Removed fontconfig

**Comment by suvari** [comment]
Fixed.
