### ISSUE TITLE
gstreamer-vaapi fix dep

### ISSUE THREAD

**Issue by ertugerata** [pisilinux/main#2163]
checkelf -s -x gstreamer-vaapi
## Unused direct dependency analysis

/usr/lib/gstreamer-1.0/libgstvaapi.so
   /lib/libpthread.so.0
/usr/lib/libgstvaapi-1.8.so.0.0.0
   /lib/libpthread.so.0
/usr/lib/libgstvaapi-x11-1.8.so.0.0.0
   /lib/libpthread.so.0
/usr/lib/gstreamer-1.0/libgstvaapi_parse.so
   /lib/libpthread.so.0
/usr/lib/libgstvaapi-glx-1.8.so.0.0.0
   /lib/libpthread.so.0
## Written dependencies           Detected dependencies          Missing dependencies

mesa                           mesa                           gstreamer-next  
yasm (devel)                   eudev (base)                   gst-plugins-base-next  
eudev (base)                   glib2 (base)  
glib2 (base)                   libva  
libva                          libX11  
libX11                         libdrm  
libdrm                         libXrandr  
gstreamer                      libXrender  
libXrandr                      gstreamer-next  
libXrender                     wayland-client  
wayland-client                 gst-plugins-base-next  
gst-plugins-bad  
gst-plugins-base

**Comment by alihanozturk** [comment]
gstreamer-vaapi paketi düzenlenecek. İçerisinden next serisi çıkarıldı ve gstreamer-vaapi-next paketi yapıldı. gstreamer-vaapi paketinin build dep lerinden next ler çıkacak.

**Comment by ertugerata** [comment]
son durum nedir ?
