### ISSUE TITLE
ses cihazını çıkartıp taktığında ses tümden gidiyor

### ISSUE THREAD

**Issue by frkntlr** [pisilinux/main#2171]
Ses cihazı yani kulaklık veya hoparlör takıp çıkarttığında sistemde ses gidiyor ve kapatıp açana kadar da geri gelmiyor. Ön panele kulaklık taktığımda arkaya takılı ses cihazı çalışmıyor

**Comment by frkntlr** [comment]
> 00:00.0 Host bridge: Intel Corporation 2nd Generation Core Processor Family DRAM Controller (rev 09)
> 00:01.0 PCI bridge: Intel Corporation Xeon E3-1200/2nd Generation Core Processor Family PCI Express Root Port (rev 09)
> 00:14.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB xHCI Host Controller (rev 04)
> 00:16.0 Communication controller: Intel Corporation 7 Series/C210 Series Chipset Family MEI Controller #1 (rev 04)
> 00:19.0 Ethernet controller: Intel Corporation 82579V Gigabit Network Connection (rev 04)
> 00:1a.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #2 (rev 04)
> 00:1b.0 Audio device: Intel Corporation 7 Series/C210 Series Chipset Family High Definition Audio Controller (rev 04)
> 00:1d.0 USB controller: Intel Corporation 7 Series/C210 Series Chipset Family USB Enhanced Host Controller #1 (rev 04)
> 00:1f.0 ISA bridge: Intel Corporation Z77 Express Chipset LPC Controller (rev 04)
> 00:1f.2 SATA controller: Intel Corporation 7 Series/C210 Series Chipset Family 6-port SATA Controller [AHCI mode] (rev 04)
> 00:1f.3 SMBus: Intel Corporation 7 Series/C210 Series Chipset Family SMBus Controller (rev 04)
> 01:00.0 VGA compatible controller: NVIDIA Corporation GF100 [GeForce GTX 465] (rev a3)
> 01:00.1 Audio device: NVIDIA Corporation GF100 High Definition Audio Controller (rev a1)
> 

sistem özellikleri

**Comment by bferturk** [comment]
#2204  güncelleme geldiğinde test edip sonuç bildirebilimisiniz ?
