### ISSUE TITLE
xawtv acılmıyor // xorg-font bağımlılığa eklenmeli

### ISSUE THREAD

**Issue by slarikan** [pisilinux/main#2172]
xawtv kurulduktan sonra açılmıyor
konsol çıktısı
xawtv
This is xawtv-3.103, running on Linux/x86_64 (4.7.2)
Warning: Color name "BACKGROUND" is not defined
xinerama 0: 1920x1080+0+0
vid-open-auto: using analog TV device /dev/video0
WARNING: No DGA direct video mode for this display.
WARNING: keeping fbuf pitch at: 7680, as no base addr was detected
WARNING: couldn't find framebuffer base address, try manual
        configuration ("v4l-conf -a <addr>")
v4l2: WARNING: framebuffer base address mismatch
v4l2: me=(nil) v4l=(nil)
Alsa devices: cap: hw:2,0 (/dev/video0), out: default
Warning: Color name "FOREGROUND" is not defined
Warning: Missing charsets in String to FontSet conversion
Warning: Missing charsets in String to FontSet conversion

**Comment by slarikan** [comment]
xorg-font paketini kurduktan sonra açıldı

**Comment by ertugerata** [comment]
fixed with https://github.com/pisilinux/main/commit/95b2482408900b3e89488035a798bdbb8b49079a
