### ISSUE TITLE
qupzilla açılışta çöküyor

### ISSUE THREAD

**Issue by slarikan** [pisilinux/main#2173]
kurulu gelen internet tarayıcımız qupzilla açılır açılmaz çöküyor
slarikan@slarikan-pc ~ $ qupzilla
QupZilla: 0 extensions loaded
AdBlockSubscription:: loadSubscription invalid format of adblock file "/home/slarikan/.config/qupzilla/profiles/default/adblock/customlist.txt" (adblock/adblocksubscription.cpp:113, virtual void AdBlockSubscription::loadSubscription(const QStringList&))
QupZilla: Crashed :( Saving backtrace in /home/slarikan/.config/qupzilla/crashlog ...
Backtrace successfully saved in /home/slarikan/.config/qupzilla/crashlog/Crash-2016-09-02T10:01:17.txt
İptal edildi
slarikan@slarikan-pc ~ $

**Comment by poyraz76** [comment]
qupzilla kaynaklı değil eklenti ile alakalı sorun
AdBlockSubscription:: loadSubscription invalid format of adblock

bu neden ile pisilinux ve qupzilla alakalı bir sıkıntı değil.

**Comment by slarikan** [comment]
Peki bu adblok böyle bir sonuç verebiliyorken neden qupzillada deault olarak gelirki?

**Comment by poyraz76** [comment]
Araçlar da Adbock seçeneği mevcut

**Comment by ertugerata** [comment]
sonuçta qupzilla hatası kapanabilir mi? @slarikan

**Comment by slarikan** [comment]
beni ilgilendirmiyo naparsanız yapın
