### ISSUE TITLE
follow newest kde-frameworks and plasma...

### ISSUE THREAD

**Issue by ertugerata** [pisilinux/main#218]
follow newest kde-frameworks and plasma if released...

**Comment by ertugerata** [comment]
Frameworks-5.13 in main https://github.com/pisilinux/main/commit/3279e10c1d1840fd9c7a837fd5c42c3c378f1ae8

**Comment by ertugerata** [comment]
- Plasma-5.4.1	Bugfix 2015-09-08	Bug fixes and new translations only from Plasma/5.4 branch
- Frameworks-5.14 tagged on Sat September 5th, released on Fri September 11th, 2015
- KDE Applications 15.08.1 tagging Thursday, September 10, 2015, release  September 15 2015

**Comment by alihanozturk** [comment]
https://www.kde.org/announcements/plasma-5.5.3.php
