### ISSUE TITLE
Kapanma sorunu

### ISSUE THREAD

**Issue by Cheopss** [pisilinux/main#2297]
Bİlgisayarı kapat dediğimde 30 saniye sonra kapanmıyor eksi saniyelere geçiyor..... Herhangi bir program yüklemesinden sonra olmadı sıfır kurulum.... pisi 2,0  30 ağustos sürümü...

**Comment by ertugerata** [comment]
bu hata tekrar ediyor mu @Cheopss

**Comment by Cheopss** [comment]
Etmiyor...
