### ISSUE TITLE
xcfe nm-applet hatası

### ISSUE THREAD

**Issue by mutlu-tekin** [pisilinux/main#2310]
nm applet wifi ile ağa bağlanırken password ekranı gelmiyor .

`(nm-applet:3716): libnotify-WARNING **: Failed to connect to proxy

(nm-applet:3716): nm-applet-WARNING **: Failed to show notification: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files

(nm-applet:3716): nm-applet-WARNING **: Failed to register as an agent: (32) An agent with this ID is already registered for this user.

(nm-applet:3716): nm-applet-WARNING **: Failed to show notification: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files

(nm-applet:3716): nm-applet-WARNING **: Failed to show notification: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files

(nm-applet:3716): nm-applet-WARNING **: Failed to show notification: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files

`

**Comment by onlined** [comment]
xfce4-notifyd kurmak çözer diye tahmin ediyorum.

**Comment by alihanozturk** [comment]
Xfce masaüstü contribe taşıdığımızdan bu hatyıda oraya taşımak gerekli.
