### ISSUE TITLE
xcfe - genel hatalar

### ISSUE THREAD

**Issue by mutlu-tekin** [pisilinux/main#2312]
1-) Öntanımlı tema düzeltilecek
2-) nm-applet şifre sorma hatası düzeltilecek
3-) başlatıcıda program ismi ararken "bib" sesi geliyor her harfe basarken
4-) zip yazılımları eksik geliyor
5-) firefox sitelere erişim hatası veriyor
6-) libre office açılış hatası veriyor

**Comment by alihanozturk** [comment]
Xfce masaüstü contribe taşıdığımızdan bu hatyıda oraya taşımak gerekli.
