### ISSUE TITLE
PackageKit desteği

### ISSUE THREAD

**Issue by ertugerata** [pisilinux/main#240]
dbus ile pisi altyapısını kullanarak paket kurma kaldırma işlemlerinin yapılması

**Comment by ertugerata** [comment]
https://github.com/ertugerata/main/commit/9b042e48e7c4a35198c0a39b339bcd9589464728 
packagekit pisi inşa dosyaları eklendi

**Comment by ertugerata** [comment]
https://github.com/calamares/calamares/issues/886 @V3n3RiX bize packagekit - pisi uyumluluğu konusunda yardım eder misiniz?

**Comment by suvari** [comment]
Fixed
