### ISSUE TITLE
kwallet için gpgme lazım

### ISSUE THREAD

**Issue by ertugerata** [pisilinux/main#254]
kwallet need optional

-- The following OPTIONAL packages have not been found:

Gpgme , GNU Privacy Guard (GPG/PGP) support , http://www.gnupg.org/related_software/gpgme Necessary to compile many PIM applications, including KMail
KF5Gpgmepp

**Comment by aydemir** [comment]
bu hata kaydının durumu nedir

**Comment by alihanozturk** [comment]
gpgme main depoya girmiş hata hala açık durumda kapanabilir
