### ISSUE TITLE
akregator

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#2548]
akregator açılmıyor.
Hata penceresinde;
KDEInit '/usr/bin/akregator' uygulamasını başlatamadı yazıyor.
konsole da hata:
akregator: symbol lookup error: /usr/lib/libakregatorprivate.so.5: undefined symbol: _ZN15WebEngineViewer13WebEngineView14dragEnterEventEP15QDragEnterEvent

**Comment by groni** [comment]
@alick01 I take a look to the package and check it

**Comment by alick01** [comment]
ınstall the new package but bugs still goes on

**Comment by alick01** [comment]
rc ile akregator açılmama hatası giderildi.Çalışıyor.Bence kapanabilir hata
