### ISSUE TITLE
kaffein

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#2600]
Başarısız.
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_LD_FLAGS

[01;31mNo file matched pattern "README".
[0m[01;33m*** 1 error(s), 0 warning(s)
[0m[01;31mProgram terminated.
[0m[01;31mNo file matched pattern "README".
[0m
http://ciftlik.pisilinux.org/ciftlik/compiledetail/13477

**Comment by groni** [comment]
Ready build http://ciftlik.pisilinux.org/ciftlik/compiledetail/13480
