### ISSUE TITLE
smplayer

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#2601]
Başarısız.
Program terminated.
[0m[01;31mActionsAPI [copytree]: Directory ../smplayer-themes-15.12.0/themes/blackPanther-Light doesn't exists.
http://ciftlik.pisilinux.org/ciftlik/compiledetail/13474

**Comment by groni** [comment]
ready build in the version http://ciftlik.pisilinux.org/2.0-Beta.1/s/smplayer/
