### ISSUE TITLE
pisiyap

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#2602]
Başarısız.
error: can't copy 'lang/pisiyap_it.qm': doesn't exist or not a regular file
[01;31mProgram terminated.
[0m[01;31mCommand "python setup.py install --root=/var/pisi/pisiyap-0.7b-1/install --no-compile -O0" failed, return value was 1.

http://ciftlik.pisilinux.org/ciftlik/compiledetail/13464

**Comment by Rmys** [comment]
Son derlenen sürüm Pisi-2.0RC Phoenix te çalışıyor sorun çözülmüş görünüyor
