### ISSUE TITLE
minuet

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#2604]
Başarısız.
Program terminated.
[0m[01;31mERROR: patch (/var/pisi/minuet/files/qtfixc.patch) failed: can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- qtfix.patch	2016-12-22 15:50:07.000000000 +0100
|+++ qtfixb.patch	2016-12-23 13:00:31.000000000 +0100
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
http://ciftlik.pisilinux.org/ciftlik/compiledetail/13106

**Comment by groni** [comment]
after remove the patch minuet could not be build

CMake Error at CMakeLists.txt:34 (find_package):
  Could not find a configuration file for package "Qt5" that is compatible
  with requested version "5.7.0".

  The following configuration files were considered but not accepted:

    /usr/lib/cmake/Qt5/Qt5Config.cmake, version: 5.6.2

**Comment by ertugerata** [comment]
build with new qt5
