### ISSUE TITLE
dolphin sol yanda sadece pisi20 kurulu olan disk görünüyor

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [pisilinux/main#262]

**Comment by ertugerata** [comment]
https://slack-files.com/files-tmb/T02NPT4LR-F098DV7QA-b6eae707a5/dolphin_720.png

**Comment by ertugerata** [comment]
son güncellemeler ile kontrol edebilir misin?

**Comment by ertugerata** [comment]
https://github.com/pisilinux/main/issues/373 , same issue.
