### ISSUE TITLE
IDLE3 Startup Error

### ISSUE THREAD

**Issue by eersoy93** [pisilinux/main#2971]
That screenshot explains the issue:

[![Screenshot](http://i.hizliresim.com/V0yZRB.png)](https://i.hizliresim.com/V0yZRB.png)

This issue can be solved with typing "xrdb -load /dev/null" to console.

**Comment by ertugerata** [comment]
renkleri qt dışı uygulamalara da uygula" ayarını bizde açık geliyor, kapatılmali mi

**Comment by suvari** [comment]
http://forum.pisilinux.org/yazilim/idle-acilmiyor

**Comment by ertugerata** [comment]
same issue https://github.com/pisilinux/main/issues/3440
