### ISSUE TITLE
Konqueror Çökme Yapıyor

### ISSUE THREAD

**Issue by Rmys** [pisilinux/main#3315]
Webte aramak yapmak istediğimizde anında çöküyor. 

Konsoldan Çalıştırdığımda çıkanlar;
mus@pisi_linux2: ~ $ sudo konqueror
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
org.kde.kurifilter-ikws: ""
org.kde.kurifilter-ikws: Keywords Engine: Loading config...
org.kde.kurifilter-ikws: Web Shortcuts Enabled:  true
org.kde.kurifilter-ikws: Default Shortcut:  ""
org.kde.kurifilter-ikws: Keyword Delimiter:  :
Trying to create view for "KonqAboutPage" "konq_aboutpage"
Found requested service "konq_aboutpage"
Trying to open lib for requested service  "konq_aboutpage"
KonqAboutPage(0x247f140) QUrl("")
KonqAboutPage(0x247f140) "khtml"
New current view KonqView(0x247fd00)
url= QUrl("about:konqueror") locationBarURL= ""
 HTML :  "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\"\n    \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\n<head>\n\t<BASE HREF=\"file:/usr/share/konqueror/about/\">\n\n  <meta name=\"generator\" content=\n  \"HTML Tidy for Linux/x86 (vers 1st August 2004), see www.w3.org\" />\n\n  <style type=\"text/css\">\n  /*<![CDATA[*/\n    @import \"file:///usr/share/kf5/infopage/kde_infopage.css\"; /* kde_infopage.css */\n     /* maybe @import \"kde_infopage_rtl.css\"; */\n    @import \"konq.css\";\n  /*]]>*/\n  </style>\n\n  <title>Be free.</title>\n</head>\n\n<body>\n  <div id=\"header\">\n    <div id=\"headerL\"/>\n    <div id=\"headerR\"/>\n\n    <div id=\"title\">\n      Konqueror \n    </div>\n\n    <div id=\"tagline\">\n      Be free. \n    </div>\n  </div>\n\n  \n  <div id=\"bar\">\n    <div id=\"barT\"><div id=\"barTL\"/><div id=\"barTR\"/><div id=\"barTC\"/></div>\n    <div id=\"barL\">\n      <div id=\"barR\">\n        <div id=\"barCenter\" class=\"bar_text\">\n          Konqueror is a web browser, file manager and universal document viewer.<br />\n          \n          <ul>\n            <li><a class=\"selected\">Starting Points</a></li>\n            <li><a href=\"about:konqueror/intro\">Introduction</a></li>\n            <li><a href=\"about:konqueror/tips\">Tips</a></li>\n            <li><a href=\"about:konqueror/specs\">Specifications</a></li>\n          </ul>\n        </div>\n      </div>\n    </div>\n    <div id=\"barB\"><div id=\"barBL\"/><div id=\"barBR\"/><div id=\"barBC\"/></div>\n  </div>\n\n  \n  <div id=\"box\">\n    <div id=\"boxT\"><div id=\"boxTL\"/><div id=\"boxTR\"/><div id=\"boxTC\"/></div>\n    <div id=\"boxL\">\n      <div id=\"boxR\">\n        <div id=\"boxCenter\">\n\t<table border=\"0\" align=\"center\">\n\t  <tr>\n\t      <td valign=\"bottom\">\n\t\t<a href=\"file:///root\"><img src=\"file:///usr/share/icons/breeze/places/32/user-home.svg\" height=\"48\" width=\"48\" /></a>\n\t\t</td>\n\t      <td valign=\"bottom\" style=\"padding-bottom: 4px; padding-left: 6px;\">\n\t\t  <a href=\"file:///root\">Home Folder</a><br><span id=\"subtext\"><nobr>Your personal files</span>\n\t\t</td>\n                <td nowrap>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>\n\t\t<td>\n\t\t    <a href=\"trash:/\"><img src=\"file:///usr/share/icons/breeze/places/32/user-trash-full.svg\" height=\"48\" width=\"48\" /></a>\n\t\t</td>\n\t      <td valign=\"bottom\" style=\"padding-bottom: 4px; padding-left: 6px;\">\n\t\t    <a href=\"trash:/\">Trash</a><br><span id=\"subtext\"><nobr>Browse and restore the trash</span>\n\t\t  </td>\n              </tr>\n              <tr><td colspan=\"5\" height=\".25em\">&nbsp;</td></tr>\n\t      <tr>\n\t\t<td>\n\t\t  <a href=\"remote:/\"><img src=\"file:///usr/share/icons/breeze/places/32/folder-remote.svg\" height=\"48\" width=\"48\" /></a>\n\t\t</td>\n\t      <td valign=\"bottom\" style=\"padding-bottom: 4px; padding-left: 6px;\">\n\t\t  <a href=\"remote:/\">Network Folders</a><br><span id=\"subtext\"><nobr>Shared files and folders</span>\n\t\t  </td>\n                <td width=\"1em\">&nbsp;</td>\n\t\t    <td>\n\t\t      <a href=\"bookmarks:/\"><img src=\"file:///usr/share/icons/breeze/places/32/bookmarks.svg\" height=\"48\" width=\"48\" /></a>\n                    </td>\n\t      <td valign=\"bottom\" style=\"padding-bottom: 4px; padding-left: 6px;\">\n\t\t       <a href=\"bookmarks:/\">Bookmarks</a><br><span id=\"subtext\"><nobr>Quick access to your bookmarks</span>\n\t\t      </td>\n\t\t</tr>\n              <tr><td colspan=\"5\" height=\".25em\">&nbsp;</td></tr>\n\t\t    </table>\n\t\t    <p id=\"nextlink\"><a href=\"about:konqueror/intro\"><img src=\"file:///usr/share/icons/breeze/actions/16/go-next.svg\" width=\"16\" height=\"16\">&nbsp;Next: An Introduction to Konqueror\n\t\t\t</a></p>\n\n        </div>\n      </div>\n    </div>\n    <div id=\"boxB\"><div id=\"boxBL\"/><div id=\"boxBR\"/><div id=\"boxBC\"/></div>\n  </div>\n\n  <div id=\"footer\"><div id=\"footerL\"/><div id=\"footerR\"/></div>\n</body>\n</html>\n\n"
kf5.kio.core: Refilling KProtocolInfoFactory cache in the hope to find ""
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
finishedLoading "file:///usr/share/kf5/infopage/kde_infopage.css"
finishedLoading "file:///usr/share/konqueror/about/konq.css"
QWidget::paintEngine: Should no longer be called
QPainter::begin: Paint device returned engine == 0, type: 1
QPainter::translate: Painter not active
QPainter::setClipRect: Painter not active
QPainter::setPen: Painter not active
QPainter::setBrush: Painter not active
QPainter::drawRects: Painter not active
QWidget::paintEngine: Should no longer be called
QWidget::paintEngine: Should no longer be called
QWidget::paintEngine: Should no longer be called
QWidget::paintEngine: Should no longer be called
QWidget::paintEngine: Should no longer be called
QWidget::paintEngine: Should no longer be called
QWidget::paintEngine: Should no longer be called
QWidget::paintEngine: Should no longer be called
QWidget::paintEngine: Should no longer be called
QWidget::paintEngine: Should no longer be called

ÇÖKME SONRASI:
[warn] epoll_wait: Dosya betimleyici hatalı
[warn] epoll_wait: Dosya betimleyici hatalı
[warn] epoll_wait: Dosya betimleyici hatalı
[warn] epoll_wait: Dosya betimleyici hatalı
[warn] epoll_wait: Dosya betimleyici hatalı
[warn] epoll_wait: Dosya betimleyici hatalı

**Comment by ertugerata** [comment]
sudo ile değil bir de normal kullanıcı olarak çalıştırın

**Comment by Rmys** [comment]
mus@pisi_linux2: ~ $ sudo konqueror start
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
org.kde.kurifilter-ikws: "start" : QUrl("http://start") , type = 8
org.kde.kurifilter-ikws: Keywords Engine: Loading config...
org.kde.kurifilter-ikws: Web Shortcuts Enabled:  true
org.kde.kurifilter-ikws: Default Shortcut:  ""
org.kde.kurifilter-ikws: Keyword Delimiter:  :
org.kde.kurifilter-ikws: "start"
org.kde.kurifilter-ikws: Keywords Engine: Loading config...
org.kde.kurifilter-ikws: Web Shortcuts Enabled:  true
org.kde.kurifilter-ikws: Default Shortcut:  ""
org.kde.kurifilter-ikws: Keyword Delimiter:  :
org.kde.kurifilter-ikws: ""
kf5.kio.core: Refilling KProtocolInfoFactory cache in the hope to find "error"
kf5.kio.core: Refilling KProtocolInfoFactory cache in the hope to find "error"
kf5.kio.core: Refilling KProtocolInfoFactory cache in the hope to find "error"
Trying to create view for "text/html" ""
"webenginepart"  : X-KDE-BrowserView-AllowAsDefault is valid :  false
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
KonqFrame(0x1cd5040) QObject(0x0)
WebEngineContext used before QtWebEngine::initialize() or OpenGL context creation failed.
WebEnginePart(0x1cda5e0) QUrl("")
WebEnginePart(0x1cda5e0) "webenginepart"
New current view KonqView(0x1cda190)
url= QUrl("error:/?error=105&errText=start#start") locationBarURL= "error:/?error=105&errText=start#start"
QUrl("error:/?error=105&errText=start#start")
ATTENTION: default value of option force_s3tc_enable overridden by environment.
KCrash: Application 'konqueror' crashing...
KCrash: Attempting to start /usr/lib/drkonqi from kdeinit
sock_file=/tmp/runtime-root/kdeinit5__0
Warning: connect() failed: : Böyle bir dosya ya da dizin yok
KCrash: Attempting to start /usr/lib/drkonqi directly
found lsb_release
Using /proc to determine executable path
Executable is: "/usr/bin/konqueror"
Executable exists: true
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Enabling drkonqi crash catching
Invalid pixmap specified.
No frame loaded
No frame loaded
No frame loaded
No frame loaded
No frame loaded
No frame loaded
ATTENTION: default value of option force_s3tc_enable overridden by environment.
Sending SIGSTOP to process

[2]+  Durdu                   sudo konqueror start
mus@pisi_linux2: ~ $

**Comment by Rmys** [comment]
son derlenen sürümlerden sonra bu sorun ortadan kalkmış görünüyor şuan normal olarak çalışıyor
