### ISSUE TITLE
acpi error

### ISSUE THREAD

**Issue by suvari** [pisilinux/main#3320]
ilk format sırası üç satırlı bir acpi... hatası çıkıyor, hemen ardından format sürüyor, fakat, format sonrasında da boot ederken, bu üç satır tepede tekrar çıkıyor, boot bu şekilde devam ediyor:

[url=http://hizliresim.com/nRlZ45][img]http://i.hizliresim.com/nRlZ45.jpg[/img][/url]
[url=http://hizliresim.com/4PzX5J][img]http://i.hizliresim.com/4PzX5J.jpg[/img][/url]

**Comment by ertugerata** [comment]
@suvari bu hata devam ediyor mu hocam?

**Comment by ertugerata** [comment]
@suvari bu hata devam ediyor mu ? ediyor ise yenidne açabilirsin
