### ISSUE TITLE
yalı'da kullanıcı otomatik giriş yapsın seçimi çalışmıyor, sddm otomatik girişe izin vermiyor

### ISSUE THREAD

**Issue by suvari** [pisilinux/main#3321]
otomatik giriş ekranı seçilerek format atılınca, sistem boot etmiyor. (slarikan)

[   194.515] _XSERVTransSocketUNIXCreateListener: ...SocketCreateListener() failed
[   194.515] _XSERVTransMakeAllCOTSServerListeners: server already running
[   194.515] (EE)
Fatal server error:
[   194.515] (EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE)
[   194.515] (EE)
Please consult the The X.Org Foundation support
     at http://wiki.x.org
for help.
[   194.515] (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
[   194.515] (EE)
[   194.515] (EE) Server terminated with error (1). Closing log file.

**Comment by suvari** [comment]
otomatik girişi tercih etmiyorum bende açılmıyor
kurulumda iki kullanıcı belirledim ama 2.inci görünmüyor
dosyaları da oluşmamış

(cengiz)

**Comment by suvari** [comment]
slarikan ın bildirimi teyit edilmedi

**Comment by ertugerata** [comment]
üstteki log daha çok X ile ilgili bir problem gibi: /var/log/Xorg.0.log hala duruyor ise onu eklese @slarikan iyi olur.

**Comment by slarikan** [comment]
/var/log/xorg.0.log paste etttim http://dpaste.com/0XSCYFM
boot.log da şöyle

INIT: version 2.88 booting

%G
[1m  Pisi_Linux 2.0RC  [0;36mhttp://www.pisilinux.org[0m

 [32;01m*[0m Kök dosya sistemi salt okunur olarak yeniden bağlanıyor
 [32;01m*[0m Kök dosya sistemi denetleniyor
Pisi: clean, 175765/3203072 files, 1441600/12799744 blocks
 [32;01m*[0m Kök dosya sistemi okunur/yazılır olarak yeniden bağlanıyor
 [32;01m*[0m Sistem adı '[37;01mpisi_linux2.0rc[0m' olarak ayarlanıyor
 [32;01m*[0m Tüm dosya sistemleri denetleniyor
 [32;01m*[0m Yerel dosya sistemleri bağlanıyor
 [32;01m*[0m /run dizini ayrılıyor
 [32;01m*[0m Takas alanı etkinleştiriliyor
 [32;01m*[0m Sistem saati donanım saatine göre ayarlanıyor
 [32;01m*[0m Tmpfiles oluşturuluyor
 [32;01m*[0m Udev servisi başlatılıyor
 [32;01m*[0m /dev içeriği dolduruluyor
 [32;01m*[0m Yerel ağ ayarlanıyor
 [32;01m*[0m Çevresel değişkenler güncelleniyor
 [32;01m*[0m /tmp dizini temizleniyor
 [32;01m*[0m DBus başlatılıyor

INIT: Entering runlevel: 3

 [32;01m*[0m Servisler başlatılıyor

**Comment by slarikan** [comment]
/var/log/sddm.log
şöyle
[17:00:08.669] (II) DAEMON: Initializing...
[17:00:08.726] (II) DAEMON: Starting...
[17:00:08.726] (II) DAEMON: Adding new display on vt 7 ...
[17:00:08.833] (II) DAEMON: Display server starting...
[17:00:08.833] (II) DAEMON: Running: /usr/bin/X -nolisten tcp -auth /var/run/sddm/{d28fd503-b382-4eb6-8222-c6e8c4c05f07} -background none -noreset -displayfd 18 vt7
[17:00:11.783] (II) DAEMON: Running display setup script  "/usr/share/sddm/scripts/Xsetup"
[17:00:11.807] (II) DAEMON: Display server started.
[17:00:11.807] (II) DAEMON: Socket server starting...
[17:00:11.807] (II) DAEMON: Socket server started.
[17:00:11.833] (II) DAEMON: Greeter starting...
[17:00:11.833] (II) DAEMON: Adding cookie to "/var/run/sddm/{d28fd503-b382-4eb6-8222-c6e8c4c05f07}"
[17:00:11.964] (II) HELPER: [PAM] Starting...
[17:00:11.964] (II) HELPER: [PAM] Authenticating...
[17:00:11.964] (II) HELPER: [PAM] returning.
[17:00:12.011] (II) DAEMON: Greeter session started successfully
[17:00:12.594] (II) DAEMON: Message received from greeter: Connect

**Comment by ertugerata** [comment]
sddm.log ve boot.log da problem gözükmüyor. http://dpaste.com/0XSCYFM Xorg.log da nvidia ile ilgili bir sorun var. 
lspci --v çıktısını da alabbilir miyiz sorunlu makinenin

**Comment by slarikan** [comment]
lspci -v çıktısını yapıştırdım http://dpaste.com/0YHDZZE

**Comment by slarikan** [comment]
nvidia kartı çıkartıp kurdum inat etti pisiyi açmıyor bilgisayar.
Xong.0.log u yeni haliyle yapıştırdım http://dpaste.com/03P0JW2

**Comment by slarikan** [comment]
otomatik girşi yapmadanda denedim olmuyor.
lxdm kurup denededim sistem açılıyor lxdm ile.
sorun galiba sddm de.

**Comment by suvari** [comment]
fixed.
