### ISSUE TITLE
Yalı dil hatası

### ISSUE THREAD

**Issue by suvari** [pisilinux/main#3322]
Yalı seçilen dili algılarken, hata yapıyor, bazı yerlerde dil, ingilizce oluyor, aynı sayfada, bazı yerler, seçilen dilde devam ediyor.

**Comment by suvari** [comment]
dil hatası @fatihkaya41 hocamın bu pr si ile çözülebilir
 https://github.com/forYali/yali/pull/3/commits/bc6a71488dd499fd10af6b0cce5415537af7136d

**Comment by ertugerata** [comment]
https://github.com/forYali/yali/pull/3/commits/bc6a71488dd499fd10af6b0cce5415537af7136d ı conflict nedeni le kapatmıştım. güncelleyip yeniden pr yapılması gerek.
