### ISSUE TITLE
pencerenin tepesi

### ISSUE THREAD

**Issue by suvari** [pisilinux/main#3324]
Açılan pencerenin tepesi, reboot etmedikçe gözükmez halde kalabiliyor, hiç bir değişiklik yapılmadan, yeniden başlatma ile kendiliğinden düzelebiliyor.
Hata sırasında, acık pencereler, panelde listelenmiyor..

**Comment by ertugerata** [comment]
örnek resim alalım...

**Comment by ertugerata** [comment]
bu hatayı son güncellemelerden sonra görmüyorum. tekrarlayan var mı?

**Comment by ertugerata** [comment]
tekrarlar ise açılabilir
