### ISSUE TITLE
grub2 diğer linux distrolarını ve kurulumları görmüyor

### ISSUE THREAD

**Issue by suvari** [pisilinux/main#3325]
Grub, format sırasında, diğer disklerdeki linux dağıtımlarını algılamadı, format sonrasında, sistem kurtarma üzerinden, grub kurtarılınca düzeldi.
Fakat cengiz, tarafından, win10 , grub kurtarma ile de eklenmedi gruba.. diye teyit edildi.

**Comment by alick01** [comment]
Evet bende ilave olarak sadece win10 var.Kurulumda eklemedi.Kurulumdan sonra flash bellekten sistemi kurtar yaptım gene olmadı. gru2-editor kurdum sistem ayarları üzerinden ekledim.grub2 gelişmiş önyükleyiciyi kurtar seçeneği ile

**Comment by ayhanyalcinsoy** [comment]
Pisi Linux oturumunda diğer dağıtımların kurulu olduğu partitionları mount ettikten sonra sudo  update-grub komutu verildiğinde diğer dağıtımlar gruba ekleniyor.

**Comment by suvari** [comment]
fixed..
