### ISSUE TITLE
package-manager yeni toolchain ile derlenmeli

### ISSUE THREAD

**Issue by suvari** [pisilinux/main#3326]
Package-manager yuklu gelmeli
Cekmecede olmali mumkunse
Pm kurdum, cekmecede goster dedim, gozukmuyor..  birkaç dakika sonra, uygulamalarda gözükür oldu, birkaç aç/kapa sonrasında, çekmecede gözükmeye başladı

**Comment by ertugerata** [comment]
bu bahsedilen hatalar mevcut ise iso da gelmemesi daha iyi değil mi?

**Comment by ertugerata** [comment]
yeni toolchain ile derlenmeli

**Comment by ertugerata** [comment]
derlendi, eksik builddep uyarısı mı var? http://ciftlik.pisilinux.org/ciftlik/compiledetail/16132

**Comment by ertugerata** [comment]
eksik depler eklendi. simge gözüküyor. 

![screenshot_20170408_144654](https://cloud.githubusercontent.com/assets/225387/24828652/3b1fb526-1c6a-11e7-880c-fd02e457ff51.png)
