### ISSUE TITLE
firefox sistem dilini algılayamıyor.

### ISSUE THREAD

**Issue by suvari** [pisilinux/main#3328]
firefox, sistem dilini algılayamıyor.

**Comment by yusufgogus50** [comment]
eklentilerdeki diller bölümüne gir.

**Comment by yusufgogus50** [comment]
etkinleştirme yap ve tamam.

**Comment by ertugerata** [comment]
otomatik olarak sistem dilini algılamalı bu şekilde ayar istememeli

**Comment by Rmys** [comment]
son sürümde bu sorun ortadan kalkmış türkçe olarak geliyor
