### ISSUE TITLE
başlat simgesi pisi ikonu olsun

### ISSUE THREAD

**Issue by suvari** [pisilinux/main#3331]
başlat simgesi, dişli olarak geliyor, kedi simgesi eklenmeli

**Comment by yusufgogus5** [comment]
bencede

**Comment by suvari** [comment]
maia kullanınca, başlat simgesi, pisi iconu oluyor kendiliğinden.. demekki diğer temalara, simgemizin eklenmesi gerekiyor,
fatihkaya41 yapabilir bunu kolaylıkla..

**Comment by alick01** [comment]
Bir değişikliğe gerek yok ki.Uygulama başlatıcıya sağ tıkla.Uygulama başlatıcı ayarlarına tıkla.Açılan penceredeki simgeye tıkla Dosyayı seç.Açılan pencereye pisi yaz gelen simgeyi seç ve onayla.Bu kadar.Her simge seti yapıldığı gibi özel olarak kalmalı bence.

**Comment by ertugerata** [comment]
pisilinux-maia teması tümden uygulanınca sorun kalmıyor. onu ön tanımlı tema yapmamız lazım

**Comment by suvari** [comment]
Fixed by Ali Algül, thanks Ali..
