### ISSUE TITLE
Yazı Tipleri ve  Firefox ayar sorunu

### ISSUE THREAD

**Issue by Rmys** [pisilinux/main#3332]
genome Gtk dan pisilinux-gtk pisilinux-firefoxu seçtiğimizde fierefoxta yazı kalmıyor karelere dönüyor
Ayarlardan yazı tiplerine girdiğimizde sabit genişlik oxygen mono 9 dğer kısımlar siyah kare kare görünüyor. Diğer kısımların fontları ayarlı gelmiyor

**Comment by ertugerata** [comment]
resim paylaşabilir misiniz?

**Comment by ertugerata** [comment]
sistem yazı fontları noto olarak ayarlanmamış gözüküyor. firefox ta bu neden ile gtk teması değiştirilince system fontlarını kullanmaya çalıştığı için problem oluyor.

**Comment by Rmys** [comment]
17.07.2017 tarihi itibarıyla son güncellemelerden sonra yazı tiplerindeki font ayarları normala dönmüş firefox görünümü ekstra bir ayar yapmadan normal olarak geliyor. (Genome uygulama biçeminde pisilinux-gtk pisilinux-firefox gibi)
