### ISSUE TITLE
libreoffice açılmıyor

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#3333]
sistemim rc ve güncel libreoffice takımından hiçbiri açılmıyor.
Konsolda /usr/lib/libreoffice/program/soffice.bin: error while loading shared libraries: liblangtag.so.1: cannot open shared object file: No such file or directory

**Comment by ertugerata** [comment]
libreoffice bağımlılıkları kararlı ya kadar düzenlecenek.

**Comment by ayhanyalcinsoy** [comment]
bağımlılıklar düzenlendi. 5.3.2.2 sürümüne yükseltildi.
