### ISSUE TITLE
Software Center (discover) çalışmıyor

### ISSUE THREAD

**Issue by Rmys** [pisilinux/main#3334]

**Comment by Rmys** [comment]
Application: Keşfet (plasma-discover), signal: Segmentation fault
[KCrash Handler]
#6  0x00007f14ab032ccb in QObject::installEventFilter(QObject*) () from /usr/lib/libQt5Core.so.5
#7  0x000000000040e526 in ?? ()
#8  0x00007f14ab02c77e in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#9  0x00007f14ab990814 in QQmlApplicationEngine::objectCreated (this=this@entry=0xc652b0, _t1=<optimized out>, _t1@entry=0x0, _t2=...) at .moc/moc_qqmlapplicationengine.cpp:153
#10 0x00007f14ab9913a2 in QQmlApplicationEnginePrivate::_q_finishLoad (this=this@entry=0xc98ca0, o=o@entry=0xcf3b70) at qml/qqmlapplicationengine.cpp:133
#11 0x00007f14ab991632 in QQmlApplicationEnginePrivate::startLoad (this=0xc98ca0, url=..., data=..., dataFlag=dataFlag@entry=false) at qml/qqmlapplicationengine.cpp:115
#12 0x00007f14ab99166d in QQmlApplicationEngine::load (this=<optimized out>, url=...) at qml/qqmlapplicationengine.cpp:260
#13 0x000000000040d3c2 in ?? ()
#14 0x0000000000409f1f in ?? ()
#15 0x00007f14aa35c3d1 in __libc_start_main () from /lib/libc.so.6
#16 0x000000000040a30a in _start ()

**Comment by ertugerata** [comment]
kirigami istiyor ? 
```
plasma-discover 
QQmlApplicationEngine failed to load component
qrc:/qml/DiscoverWindow.qml:6 module "org.kde.kirigami" is not installed
KCrash: Application 'plasma-discover' crashing...
KCrash: Attempting to start /usr/lib/drkonqi from kdeinit
sock_file=/tmp/1000-runtime-dir/kdeinit5__0
```

**Comment by hknyldz** [comment]
@ertugerata evet abi kirigami istiyor.

**Comment by ertugerata** [comment]
kirigami paketleyelim ya da başka bir yol bulalım

**Comment by ertugerata** [comment]
kirigami depoda, şuı anda problem var mı?
