### ISSUE TITLE
skrooge açılmıyor

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#3335]
cengiz@Kurt: ~ $ skrooge
skrooge: error while loading shared libraries: libsqlcipher-3.8.10.2.so.0: cannot open shared object file: No such file or directory
cengiz@Kurt: ~ $ sudo pisi sf libsqlcipher
Parola: 
libsqlcipher aranıyor
sqlcipher paketi içinde usr/lib/libsqlcipher.so dosyası var.
sqlcipher paketi içinde usr/lib/libsqlcipher-3.11.0.so.0 dosyası var.
sqlcipher paketi içinde usr/lib/libsqlcipher-3.11.0.so.0.8.6 dosyası var.
cengiz@Kurt: ~ $

**Comment by ertugerata** [comment]
pisi li -b farmV2 çıktısını paylaşır mısınız?

**Comment by alick01** [comment]
cengiz@Kurt: ~ $ pisi li -b farmV2
akregator           - KDE Pim different packages with akonadi-console, kadressbook blogilo etc
filezilla           - FTP ve SFTP istemcisi
freshplayerplugin   - ppapi2npapi compatibility layer
gweled              - "Bejeweled" veya "Diamond Mine" benzeri bir bulmaca oyunu
kdepim-common       - KDE Pim different packages with akonadi-console, kadressbook blogilo etc
kdepim-runtime      - KDE5 PIM (Kişisel Bilgi Yönetimi) çalışma zamanı ortamı
libgphoto2          - Sayısal kamera ve müzik çalarlara erişim sağlayan kütüphane
libieee1284         - IEEE1284 kullanarak donanımların sorgulanması için bir kütüphane
mailimporter        - Mail importer library
messagelib          - KDE PIM library providing support for mail applications
package-manager     - PiSi kullanıcı grafik arayüzü
physfs              - Dosya sistemi kitaplığı
sane-backends       - SANE (Scanner Access Now Easy) döküman ve resim tarayıcı sistemi araçları
skrooge             - Kişisel finansal yönetici
thunderbird         - Thunderbird eposta istemcisi
thunderbird-lang-tr - Thunderbird için Türkçe dil dosyası
wxGTK               - Birçok platform için ortak C++ arayüz araç takımı olan wxWindows'un GTK+ sürümü

**Comment by ertugerata** [comment]
sqlcipher güncellemesi skrooge u kırmış. çünkü yeni toolchain ile henüz derlenmemiş. bu üstte ççıkan paketlerde aynı durumda onların herbir yeni toolchain ile derlenmeli. bu konuda tek tek issue açabilir misiniz?

**Comment by alick01** [comment]
skrooge yerelde derledim çalışıyor bir problem yok

**Comment by alick01** [comment]
güncellemeleri yaptım skrooge çalışmadı yerelde derledim çalıştı. yeniden derlenmesi gerek

**Comment by alick01** [comment]
Güncellemelerden sonra derlenen skrooge yi betadan güncelledim çalışıyor kapanabilir.

**Comment by suvari** [comment]
fixed
