### ISSUE TITLE
Gonullu paketi bağımlılıkları ile birlikte güncellenmeli

### ISSUE THREAD

**Issue by ertugerata** [pisilinux/main#3362]

**Comment by ertugerata** [comment]
pisi den kurduğumu çalıştırmak istedim. olmayınca github dan kurdum. 

`sudo gonullu
Parola: 
Traceback (most recent call last):
  File "/usr/bin/gonullu", line 8, in <module>
    from gonullu import Log, Farm, Volunteer
  File "/usr/lib/python3.6/site-packages/gonullu/__init__.py", line 2, in <module>
    from gonullu.docker import Docker
  File "/usr/lib/python3.6/site-packages/gonullu/docker.py", line 6, in <module>
    from docker import Client
  File "/usr/lib/python3.6/site-packages/docker/__init__.py", line 2, in <module>
    from .api import APIClient
  File "/usr/lib/python3.6/site-packages/docker/api/__init__.py", line 2, in <module>
    from .client import APIClient
  File "/usr/lib/python3.6/site-packages/docker/api/client.py", line 11, in <module>
    from .build import BuildApiMixin
  File "/usr/lib/python3.6/site-packages/docker/api/build.py", line 8, in <module>
    from .. import auth
  File "/usr/lib/python3.6/site-packages/docker/auth.py", line 6, in <module>
    import dockerpycreds
ModuleNotFoundError: No module named 'dockerpycreds'`


 `sudo pip3 install git+https://github.com/PisiLinuxNew/gonullu.git
Collecting git+https://github.com/PisiLinuxNew/gonullu.git
  Cloning https://github.com/PisiLinuxNew/gonullu.git to /tmp/pip-u2vfk9ks-build
Requirement already satisfied: argparse in /usr/lib/python3.6/site-packages (from Gonullu==1.1.5)
Requirement already satisfied: requests in /usr/lib/python3.6/site-packages (from Gonullu==1.1.5)
Collecting docker-py (from Gonullu==1.1.5)
  Downloading docker_py-1.10.6-py2.py3-none-any.whl (50kB)
    100% |████████████████████████████████| 51kB 416kB/s 
Requirement already satisfied: psutil in /usr/lib/python3.6/site-packages (from Gonullu==1.1.5)
Requirement already satisfied: colorama in /usr/lib/python3.6/site-packages (from Gonullu==1.1.5)
Collecting pyaml (from Gonullu==1.1.5)
  Downloading pyaml-16.12.2-py2.py3-none-any.whl
Collecting six>=1.4.0 (from docker-py->Gonullu==1.1.5)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting docker-pycreds>=0.2.1 (from docker-py->Gonullu==1.1.5)
  Downloading docker_pycreds-0.2.1-py2.py3-none-any.whl
Requirement already satisfied: websocket-client>=0.32.0 in /usr/lib/python3.6/site-packages (from docker-py->Gonullu==1.1.5)
Collecting PyYAML (from pyaml->Gonullu==1.1.5)
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 299kB/s 
Installing collected packages: six, docker-pycreds, docker-py, PyYAML, pyaml, Gonullu
  Running setup.py install for PyYAML ... done
  Found existing installation: Gonullu 1.1.3
    Uninstalling Gonullu-1.1.3:
      Successfully uninstalled Gonullu-1.1.3
  Running setup.py install for Gonullu ... done
Successfully installed Gonullu-1.1.5 PyYAML-3.12 docker-py-1.10.6 docker-pycreds-0.2.1 pyaml-16.12.2 six-1.10.0`

**Comment by ertugerata** [comment]
bunların hepsi bizde var mı? 

`Gonullu-1.1.5 PyYAML-3.12 docker-py-1.10.6 docker-pycreds-0.2.1 pyaml-16.12.2 six-1.10.0`

**Comment by ayhanyalcinsoy** [comment]
python3-docker-py paketinin yeni sürümü ile gonullu uyumsuz olduğundan çalışmıyormuş. 
python3-docker-py sürüm 1.8.1 olarak ayarlandı ve Hata giderildi.
