### ISSUE TITLE
isodumper açılmıyor!

### ISSUE THREAD

**Issue by yusufgogus5** [pisilinux/main#3375]
File "/usr/lib/isodumper/isodumper.py", line 762
    self.img_name=yui.YUI.app().askForExistingFile('file:///home/'+self.user,"*.iso *.img",self.ChooseImage))
                                                                                                            ^
SyntaxError: invalid syntax
 hatası veriyor.

**Comment by ertugerata** [comment]
http://gitweb.mageia.org/software/isodumper cevap vermiyor. verince kontrol edilecek.

**Comment by alick01** [comment]
762 satırın sonunda fazladan bir parantez var onu kaldırdım çalıştırdım şifre girince bu sefer yui modülünü bulamadım dedi
Traceback (most recent call last):
  File "/usr/lib/isodumper/isodumper.py", line 37, in <module>
    import yui
ModuleNotFoundError: No module named 'yui'

**Comment by alick01** [comment]
py3parted paketini yerelde derleyip yükledim ama yukarıdaki hata çıkıyor.O modülüde bulamadım sf ile

**Comment by yusufgogus501** [comment]
2.0 beta 2'de mis gibi çalışıyor ama RC'de kötüydü en son şimdi nasıl?

**Comment by Rmys** [comment]
İsodumper mevcut depomuzdaki programlar ile ancak 0.48 sürümüne kadar çalışıyor. 0.48 den sonraki sürümler libyui and declanation of ncurses, gtk or Qt libyui-mga gibi programlar istediğinden derlensede çalışmıyor. Çalışan en son sürüm 0.48

**Comment by alick01** [comment]
beta1 depodaki 0.45 sürümünü yükledim çalışıyor.0.55 i silersek 0.45 iş görür veya 0.48 e güncellenebilir

**Comment by Rmys** [comment]
0.48 e dönebiliriz ben dahil kullanan arkadaşlar var

**Comment by ertugerata** [comment]
isodumper-0.55 i depodan siliyorum siz de 0.48 çekin sürümü

**Comment by ertugerata** [comment]
0.48 depoda
