### ISSUE TITLE
kurulum sonu

### ISSUE THREAD

**Issue by makinemuh** [pisilinux/main#3380]
![dsc_0001](https://cloud.githubusercontent.com/assets/9573526/24839222/1a398940-1d5f-11e7-87d5-61b57b313667.JPG)
![dsc_0002](https://cloud.githubusercontent.com/assets/9573526/24839226/24e6536e-1d5f-11e7-880e-d037e34b3bd8.JPG)
![dsc_0003](https://cloud.githubusercontent.com/assets/9573526/24839228/2bb40a56-1d5f-11e7-89a4-ed69ff6e92ae.JPG)

**Comment by yusufgogus5** [comment]
Ekranı ayarlayın.

**Comment by makinemuh** [comment]
nasıl bir ayardan bahsediyorsunuz hocam

**Comment by yusufgogus501** [comment]
gerçii ayarı yok 30 ağustos sürümünü yükleyin ve tekrar yazın

**Comment by makinemuh** [comment]
ısınma problemi sebebiyle yüklemiyorum henuz onun biz çözümü varsa yükleyeyim hocam teşekkürler

**Comment by yusufgogus501** [comment]
yeni işlemci alın bence veya yeni ekran kartı alın.

**Comment by yusufgogus501** [comment]
bende pek bilemedim bilgisayarcıya bi götür derim

**Comment by yusufgogus501** [comment]
işleciyi değiştirin ama baya para isterler.internetten araştırın.

**Comment by ertugerata** [comment]
bu kurulum hatasının nedenini bulmamız lazım. ısınma bende fark edilir derecede değil.

**Comment by makinemuh** [comment]
@ertugerata açık kaynak sürücülerimi kullanıyorsunuz ?  bu kurulum problemi safe mode ile alaklı olabilirmi

**Comment by suvari** [comment]
fixed
