### ISSUE TITLE
Bildirimden flash bellek dizini açılmıyor

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#3396]
Bellek takıldığında bildirim üzerinden flash bellek dizinini açılmıyor.İzin sorunu ortaya çıkıyor.
Bunun için /media/kullanıcı_dizininin sahip ve gurubunu değiştirerek kullanıcı ve gurubunu atamak gerekiyor.

**Comment by ertugerata** [comment]
ilk kurulumda /media altında o dizin oluşmuş mu?

**Comment by alick01** [comment]
Ben oluşturmadım herhalde oluşmuş kurulumda

**Comment by alick01** [comment]
Şimdi yeni kullanıcı ekledim.media dizininde kullanıcı dizini oluşmadı ancak flash takıp bağlayınca dizin oluşyor ama root sahipliğinde

**Comment by alick01** [comment]
şu anda bir sorun görünmüyor
