### ISSUE TITLE
IDLE for Python 3.x can't be launched

### ISSUE THREAD

**Issue by eersoy93** [pisilinux/main#3440]
On Pisi 2.0 RC, I get that output when I try to launch IDLE for Python 3.x:
```
eersoy93@pisivbox: ~ $ idle3
Traceback (most recent call last):
  File "/usr/lib/python3.6/idlelib/pyshell.py", line 4, in <module>
    from tkinter import *
  File "/usr/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/idle3", line 3, in <module>
    from idlelib.pyshell import main
  File "/usr/lib/python3.6/idlelib/pyshell.py", line 7, in <module>
    "Your Python may not be configured for Tk. **", file=sys.__stderr__)
NameError: name 'sys' is not defined
eersoy93@pisivbox: ~ $ 
```

**Comment by eersoy93** [comment]
See for solution: https://bugs.python.org/issue24759

**Comment by ertugerata** [comment]
beta depodan python3-tk paketini kurup dener misiniz, hata devam ediyor mu?

**Comment by Rmys** [comment]
http://forum.pisilinux.org/yazilim/idle-acilmiyor
Python3 deki son rebuild ten sonra pisi forumda verilen komutlar ile çalıştı idle3 çalışmaya başladı

**Comment by Rmys** [comment]
Konsoldan;
xrdb -load /dev/null
xrdb -query

ya da

kde sistem ayarları> uygulama görünümü > renkler >Seçenekler > Renkleri KDE dışı uygulamalara da uygula
tikini kaldırıp Uygulamak gerekiyor.
Kayıtlı

**Comment by ertugerata** [comment]
çözüldü
