### ISSUE TITLE
Kaptan

### ISSUE THREAD

**Issue by ghost** [pisilinux/main#3474]
KAPTAN amca bilgisayarı yönetmiyor ve hiçbir şekilde duvar kağıdı ayarlamıyor.

**Comment by mthnzbk** [comment]
konsoldan kaptan komutunu çalıştırıp dene ve çıktıları yapıştır. Bu şekilde bir şey yapılamaz.

**Comment by ertugerata** [comment]
hangi sürüm? RC üzerinde sıfır kurulumda kaptan otomatik olarak bailıyor ve duvar kağıdını ayarlıyor. ayrıntılı açıklama ve resim gerekli. bence hata wontfix..

**Comment by yusufgogus501** [comment]
2.0 beta 2 ertuğrul abi

**Comment by yusufgogus501** [comment]
RC kurdum

**Comment by Rmys** [comment]
Sistemi ilk kurduktan sonra bir kaç oturum duvar kağıdını değiştirmiyor sonraki açılışlarda kendine geliyor değiştirmeye başlıyor
