### ISSUE TITLE
Pisi-2.0RC Phoenix problemleri

### ISSUE THREAD

**Issue by groni** [pisilinux/main#3475]
Installation from Pisi-2.0RC Phoenix was ok, no problems with Yali

After the Installation:
Grub2 detects no other OS
No SDDM Login-Screen, Pisi Linux has started with a black screen 
Keyboard Layout was English, and i have set German by the Installation
Language in German was not installed

All other was ok i have at the moment not detect more Issues

**Comment by yusufgogus501** [comment]
Groni Bendede Yalı ingilizce ve sadece bir kısmı türkçe.Bunu yeni sürümde kusursuzlaştırsınlar bence

**Comment by suvari** [comment]
Fixed.
