### ISSUE TITLE
Pisilinux-Welcome(Pisilinux'a Hoşgeldiniz ekranı) Açılmıyor neden?

### ISSUE THREAD

**Issue by yusufgogus501** [pisilinux/main#3498]
Bence Hem Açılmalı Hemde Yeni Özellikler eklenmeli(örnek:Müzik https://www.youtube.com/watch?v=QWVu2yeclvs bu videodaki Allah-u Ekber,Allah-u Ekber Türkler Geliyor tarafı ) tabii ki mümkünse.

**Comment by ertugerata** [comment]
Geçersiz. bence bir issue girişi için sebep değildir. kendi bilgisayarınızda istediğiniz özelleştirmeleri yapabilirsiniz.
