### ISSUE TITLE
Inkscape yeni toolchain ile derlenmeli 

### ISSUE THREAD

**Issue by ghost** [pisilinux/main#3505]
Inkscape Açılmıyor Tıklayınca.

**Comment by yusufgogus501** [comment]
gerçekten açılmıyor

**Comment by ertugerata** [comment]
konsoldan çalıştırıp hata çıktısını paylaşır mısınız

**Comment by yusufgogus501** [comment]
inkscape: error while loading shared libraries: libgsl.so.0: cannot open shared object file: No such file or directory
böyle bir hata.

**Comment by yusufgogus501** [comment]
Ayrıca Ghost Adlı Hesap Benim Önceki Github Hesabım.

**Comment by ertugerata** [comment]
`pisi li -b | grep farmV3` çıktısını paylaşır mısın?

**Comment by ertugerata** [comment]
Latest stable version: Inkscape 0.92.1 
bu sürüme geçelim

**Comment by ertugerata** [comment]
teşekkürler https://github.com/aligulle1

**Comment by aligulle1** [comment]
görevim abi
