### ISSUE TITLE
LibreOffice 5.3 - Fatal Error

### ISSUE THREAD

**Issue by vdemir** [pisilinux/main#3512]
Uygulama başlatılamadı.

**Comment by yusufgogus501** [comment]
libreoffice-help-tr Adlı Paketi Kurmayı Deneyin.

**Comment by ertugerata** [comment]
konsoldan herhangi birini çalıştırarak log u paylaşır mısınız

**Comment by vdemir** [comment]
![screenshot_20170516_192132](https://cloud.githubusercontent.com/assets/7329803/26116775/f7e414b6-3a6c-11e7-9fa4-0154879bef76.png)

**Comment by alick01** [comment]
Bende resimdeki sorun ortaya çıkıyor.Konsole de;
cengiz@Kurt: ~ $ libreoffice --writer user.odt
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
** (soffice:12332): WARNING **: AT-SPI: Could not obtain desktop path or name
** (soffice:12332): WARNING **: atk-bridge: GetRegisteredEvents returned message with unknown signature
** (soffice:12332): WARNING **: atk-bridge: get_device_events_reply: unknown signature
** (soffice:12332): WARNING **: atk-bridge: get_device_events_reply: unknown signature
cengiz@Kurt: ~ $

**Comment by ismetsezer** [comment]
Yeniden yuklemeyi denediniz mi  yada  libreoffice daha once update ettiyseniz localden dolayi sorunlar olusabiliyor

**Comment by alick01** [comment]
eksik bağımlılık medeniyle lo hata veriyordu.Giderilmişti.Bence kapanabilir bu hata.
