### ISSUE TITLE
Hostname doesn't be changed.

### ISSUE THREAD

**Issue by eersoy93** [pisilinux/main#3523]
When I edit /etc/hostname and /etc/hosts via text editor with root authorities and appropriate changes, the hostname doesn't be changed after reboot.

Pisi version: 2.0 RC

**Comment by suvari** [comment]
Hatayı tekrarlayamadım, bende değişti

**Comment by eersoy93** [comment]
Hostname didn't changed after rebooting for me. See: https://dpaste.de/dbvm/raw

**Comment by eersoy93** [comment]
"sudo hostname -v --file /etc/hostname" with rebooting didn't change. See: dpaste.com/1F7B0Z8

**Comment by ertugerata** [comment]
etc/hostname bizde bulunmuyor.hata geçersiz.
