### ISSUE TITLE
Sistem hatası. Program sonlandırıldı.

### ISSUE THREAD

**Issue by vdemir** [pisilinux/main#3533]
kdepim-common sürüm 2 bağımlılığı kmail paketi için sağlanamadı.

**Comment by alick01** [comment]
kdepim paketlerinde 16.12 sürümle yeni bir yapılanmaya geçildi diye biliyorum.bende 16.12 versiyonlar (kmail kontact korganizer) kurulu ve kdepim-common yerine pimcommon kullanıyorum

**Comment by ertugerata** [comment]
hangi depoda var bu bahsettiğiniz problem

**Comment by alick01** [comment]
Beta1 depodayım ancak 16.12 sürümlerini yerelde derledim ve onlarla pimcommon paketini kullanıyorum.kdepim-common ile 16.12 ler hata veriyor.

**Comment by vdemir** [comment]
@ertugerata @suvari @ayhanyalcinsoy aklımda bir proje var.  forum-wiki-soru_cevap-projelerle ilgili tek bir statik site içinde hepsi bir arada bir yapı olabilir. Bir tane şablon var aklımda. İçeriğinin önceden hazırlanıp paylaşıldığı ve yeni içeriklerin zamanla cevaplanarak eklendiği bir bilgi kaynağı, çözüm içerikli ve katkıcılar için başlangıç yeri. iletişimde kalacağımız bir mesaj kanalı varsa zaman buldukça girip gelişmeleri paylaşabilirim.

**Comment by ertugerata** [comment]
https://gitter.im/pisilinux olabilir

**Comment by ertugerata** [comment]
hatalar tekrarlanıyor mu? son güncellemeler ile çözülmüş olmalı. tekrarlar ise yeniden açar mısınız?
