### ISSUE TITLE
usbmuxd -libusbmuxd sorunu

### ISSUE THREAD

**Issue by Rmys** [pisilinux/main#3558]
usbmuxd'un tüm sürümleri libusbmuxd dosyası ile derlenmiş ancak son derlenen sürüm usbmuxd dosyası ile derlendiğinden şuan sorun var usbmuxd-devel isteyen programlar usbmuxd-devel dosyasını bulamıyor. bir düzeltme yapılması gerekli usbmuxd ve libusbmuxd olarak iki dosya veya usbmuxd olarak eski düzen devam etmeli eski düzen devam edecekse usbmuxd-1.1.0-5-p2-x86_64.pisi  dosyasının silinmesi gerekiyor.  usbmuxd ile libusbmuxd birbirinden tamamen farklı iki program

**Comment by ertugerata** [comment]
anlamadım, ama upower de kırılmış

**Comment by Rmys** [comment]
libusbmuxd olarak derleme işlemi yapıldı usbmuxd-devel isteyen programların bağımlılıkları libusbmuxd-devel olarak düzeltilerek Rebuild edildi sorun çözüldü
