### ISSUE TITLE
Kurulumda diski silememe hatası

### ISSUE THREAD

**Issue by namso-01** [pisilinux/main#358]
Pisi 2.0 yalı kurulum esnasında seçilen diski silemiyor, hata veriyor, devam etmiyor

Ntfs olan diğer diskleri ise unknown olarak görüyor.

**Comment by ertugerata** [comment]
bu konuda @poyraz76 nın yaptığı araştırmada ntfs modulü isim değiştirmiş gibi gözüküyor, nfts -->> ntfs-3g
bu nedenle ntfs bölümler görülmüyor olabilir. Açılışta konsolda takas var ise aktif edildiğinde bu hata vermiyordu. bir deneyebilir misiniz?

**Comment by namso-01** [comment]
Nasıl yapılıyordu, bir de el ile değil de otomatik nasıl yaparız. Normal kullanıcıyı aşarda

**Comment by ertugerata** [comment]
ntfs

**Comment by namso-01** [comment]
ntfs konusunda ne yapmıştık, hatırlaymadım.

Calamaras'a geçecek ise yalı ne olacak sorusu aklıma gelince bu hata kaydının bir anlamı kalmıyor.

**Comment by ertugerata** [comment]
Acaba gecilecek mi
