### ISSUE TITLE
Dağıtımlar için yeni bir geliştirme ortamı 

### ISSUE THREAD

**Issue by vdemir** [pisilinux/main#3588]
https://hub.docker.com/r/yesnault/docker-phabricator/
hazır docker kurulumu var
kde neon ve solus aktif kullanmakta
https://dev.solus-project.com
https://phabricator.kde.org

**Comment by ertugerata** [comment]
bakımı yapılmıyor nasıl kullanıldığının anlaşılması lazım. deneyimli birisi bilgi verebilir. bir hata değil iyileştirme. buradan devam edilmesine gerek yok.
