### ISSUE TITLE
could not start ksmserver. check your installation hatası

### ISSUE THREAD

**Issue by prdsmehmetstc** [pisilinux/main#362]
yaklaşık her 5-10 dk da bir could not start ksmserver. check your installation hatası verip giriş ekranına atıyor. o pencereye okay dersem daha da açılmıyor kde. sanal makinede kurulum yaptım..

**Comment by ertugerata** [comment]
normal sistemde görünen hata yok. xsession-errors, dmesg çıktılarını eklemelisin.
