### ISSUE TITLE
SDDM Teması değişmiyor.

### ISSUE THREAD

**Issue by prdsmehmetstc** [pisilinux/main#363]
SDDM Temasını değiştirmeye çalıştığımda maui temasında kalıyor. Herhangi bir temayı seçip uygula'ya bastığımda ne şifre soruyor ne de başka bir şey. Geri dönüp tekrar girdiğimde ise maui temasında takılı kaldığını görüyorum.

**Comment by ertugerata** [comment]
bende şifre soruyor ve tema değişiyor. Alfa5, güncel sistem.

**Comment by aydemir** [comment]
bende de şifre sormuyor iso da yetkilendirme modulleri varmı

**Comment by prdsmehmetstc** [comment]
Ben alfa4 ten alfa5 e güncelleyince sorun çözüldü.
