### ISSUE TITLE
Pisi Linux 2.0 dolphin detects no other partition, no CD/DVD drive

### ISSUE THREAD

**Issue by groni** [pisilinux/main#373]
Pisi Linux 2.0 has any issues, it detects no USB Devices, no other partition and it detects  CD/DVD drive not
I hope it can be solving

**Comment by ertugerata** [comment]
same issue #262

**Comment by ertugerata** [comment]
is resolved in plasma-5.5.0 https://bugs.kde.org/show_bug.cgi?id=351003

**Comment by ertugerata** [comment]
https://github.com/pisilinux/core/commit/8a00ea6d3a1d39f42489021a8a118493beaa2c01 ile usb diskler bağlanıyor.

**Comment by groni** [comment]
I have delete USB Device in the isuue while it works

**Comment by ertugerata** [comment]
https://github.com/pisilinux/core/commit/14aa28d68f4abfbedf5a8328754ea8289090dd96 son eudev güncellemesi ile disk bölümlerinin bağlanması konusu da hallolmuş olmalı. 

pisi up -dsy ile güncelleyerek dener misiniz?

**Comment by ertugerata** [comment]
Sonuç ?

**Comment by groni** [comment]
All ok now USB CD/DVD and partitions are detect, issue is solved
