### ISSUE TITLE
asus g72gx uyanamama sorunu

### ISSUE THREAD

**Issue by erkanisik1** [pisilinux/main#3741]
bilgisayarı hazırda beklet dediğimizde sorunsuz hemen uykuya geçiyor ama bilgisayarı uyandırdığımızda ekran açılmıyor, ekran arkaplan ışığı dahi yanmıyor. Tamamen kapatıp açtığımızda sorunsuz devam ediyor.

**Comment by erkanisik1** [comment]
sorun kendi kendine düzeldi, şu an için sıkıntı yok görünüyor

**Comment by ertugerata** [comment]
takip edelim, yeniden olur ise detaylı log bulursanız yeniden açarsınız.
