### ISSUE TITLE
Ağ Hatası - paket yöneticisi

### ISSUE THREAD

**Issue by erkanisik1** [pisilinux/main#3742]
bazen paket yöneticisi **Lütfen ağ ayarlarınızı kontrol edin ve tekrar deneyin.** uyarısını veriyor ve paket kurulumu yapmıyor, komut satırından normal yükleme yappılabiliyor

**Comment by ertugerata** [comment]
ping?

**Comment by erkanisik1** [comment]
normalde internet bağlantısında sıkıntı yok o sırada radyoda dinliyorum genelde ama bazen bağlantı yok diyebiliyor ve paket yöneticisini kapatıp açınca işlemleri yapıyor

**Comment by erkanisik1** [comment]
sorun hala devam etmekte nm1.10.0 sürüü yüklendiğinde bağlanabiliyor ama simgesinde bağlantı yok gösteriyor.

**Comment by ertugerata** [comment]
devam ederse yeniden açabilirsiniz?
