### ISSUE TITLE
kdeconnect telefonu bulamıyor

### ISSUE THREAD

**Issue by erkanisik1** [pisilinux/main#3860]
sistem ayarlarından kdeconnetce tıkladığımda ayar ekranı geliyor refresh dediğimde bir şey bulamıyor, var/log da herhangi bir hata kaydı yok, konsoldan ~ $ **kdeconnect-cli** dediğimde **No device specified** diyor.

**Comment by alick01** [comment]
bu paket için ubuntu sayfalarında bunu buldum:
http://www.omgubuntu.co.uk/2017/01/kde-connect-indicator-ubuntu
indicator-kdeconnect paketinin yüklenmesi gerek diyor.
paket burada https://launchpad.net/~varlesh-l

**Comment by alick01** [comment]
indicator-kdeconnect paketi içinde kde plasma olmayan sistemler içinmiş.

**Comment by alick01** [comment]
Mustafa Cinasal önerdi qca2-qt5-2.1.3-4-p2-x86_64.pisi ile güncelledim.kdeconnect çalışıyor mükemmel.
hata kapanabilir bence.

**Comment by erkanisik1** [comment]
evet qca2-qt5-2.1.3-4-p2-x86_64.pisi paketini yükleyince kdeconnect sorunsuz çalıştı.
