### ISSUE TITLE
xmoto

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#4196]
açılmıyor.lua51 yükledikten sonra;
fatal exception : SDL_SetVideoMode : X11 driver not configured with OpenGL

**Comment by Rmys** [comment]
libsdl nin build bağımlılığına mesa-devel ve mesa-glu-devel eklenerek rebuild edilecek sonra xmoto rebuild edilecek

**Comment by Rmys** [comment]
Written dependencies           Detected dependencies          Missing dependencies
----------------------------------------------------------------------------------
ode                            ode                                                          
curl (base)                    curl (base)                                                  
mesa                           mesa                                                         
zlib (base)                    zlib (base)                                                  
bzip2 (base)                   bzip2 (base)                                                 
lua51                          lua51                                                        
libgcc (base)                  libgcc (base)                                                
libpng                         libpng                                                       
libsdl                         libsdl                                                       
sqlite (base)                  sqlite (base)                                                
libxml2 (base)                 libxml2 (base)                                               
sdl-net                        sdl-net                                                      
sdl-ttf                        sdl-ttf                                                      
mesa-glu                       mesa-glu                                                     
sdl-mixer                      sdl-mixer                                                    
libjpeg-turbo                  libjpeg-turbo  

xmotonun çalışma bağımlılıkları düzeltilecek

**Comment by alick01** [comment]
libsdl güncellemelerini yükledim xmoto tamam teşekkürler
