### ISSUE TITLE
efitools:PreLoader.efi dosyası oluşmuyor

### ISSUE THREAD

**Issue by Rmys** [pisilinux/main#4221]
PreLoader.efi dosyası oluşmuyor

https://bugs.archlinux.org/task/49314

https://git.kernel.org/pub/scm/linux/kernel/git/jejb/efitools.git/tree/Makefile#n8

**Comment by ertugerata** [comment]
https://github.com/pisilinux/main/commit/477ecb0e4ac5ab119b9a2fa9d91fbd136e53d2c4 ile çözüldü.
