### ISSUE TITLE
Uygulama başlatıcı

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#451]
Uygulama başlatıcı Geçmiş sekmesinde bulunan daha önce kullanılmış dosyaların üzerine tıkladığımda dosya açılmıyor.Ofis resim pdf v.b gibi

**Comment by ertugerata** [comment]
yeni plasma sürümünde (5.5) giderilmiş gözüküyor test eder misiniz?

**Comment by ertugerata** [comment]
hata giderilmiş
