### ISSUE TITLE
ConsoleKit

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#460]
Başarısız http://ciftlik.pisilinux.org/ciftlik/compiledetail/932

**Comment by ertugerata** [comment]
eski build log, paet depoda.

**Comment by ertugerata** [comment]
https://github.com/pisilinux/main/commit/b8e55cf5014e3b0095aea2c48755b16d08da3021

**Comment by ertugerata** [comment]
@alick01 teşekkürler. Source ismi ile paket ismi aynı olmadığından patlamış dikkatimizi çekmemiş.

**Comment by ertugerata** [comment]
paket depoda.
