### ISSUE TITLE
2.0 Kararlı UEFI kurulum sonrası Kaptan her başlangıçta açılıyor.

### ISSUE THREAD

**Issue by prdsmehmetstc** [pisilinux/main#4839]
2.0 kararlı sürümü UEFI olarak kurduğumda her başlangıçta Kaptan'ın tekrar tekrar açıldığını farkettim. Legacy kurulumda bu sorun yok.

**Comment by ertugerata** [comment]
2.1 e bunu tekrarlıyor musunuz?

**Comment by suvari** [comment]
Fixed.
