### ISSUE TITLE
qtcreator

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#561]
Başarısız http://ciftlik.pisilinux.org/ciftlik/compiledetail/907

**Comment by ertugerata** [comment]
llvm > 3.60 ister.

**Comment by ayhanyalcinsoy** [comment]
qtreator 3.5.1 hazır. ancak qt5-base-devel da bulunan mkspec dizinindeki dosyaların qt5-base olması gerekiyor. 
qtcreator-3.5.1 > hazır
qt5-base-5.5.1 > hazır

**Comment by huseyinkozan** [comment]
2.0 alfa 6 da; qtcreator 3.4.2 de /usr/bin/qtcreator.sh dosyası için şunları yapınca çalıştı :

```
sudo chmod +x /usr/bin/qtcreator.sh
sudo sed -i -e 's/LD_LIBRARY_PATH=\/usr\/lib\/qtcreator QT_LOGGING_TO_CONSOLE=1/QT_LOGGING_TO_CONSOLE=1/g' /usr/bin/qtcreator.sh
```

**Comment by ertugerata** [comment]
@huseyinkozan üstteki işleme gerek kalmayacak. @ayhanyalcinsoy tamamladı qtcreator'u. farm da build edeceğiz.

**Comment by alick01** [comment]
Tasarımcı bende çalışıyor
