### ISSUE TITLE
Paket İsteği

### ISSUE THREAD

**Issue by FreeVirtualWorld** [pisilinux/main#5646]
Linux oyuncularının sevgili dostu Steam uygulamasını deponuza eklemenizi istiyor ve tavsiye ediyorum.
[https://store.steampowered.com/about/](url)
Doğrudan İndirme Linki: [https://steamcdn-a.akamaihd.net/client/installer/steam.deb](url)

**Comment by ertugerata** [comment]
vermiş olduğunuz link bir dep dosyası, yani debian paketleme sistemine ait. steam bir takım çözümlerimiz var. bunlardan birisi flatpak ile kurmak diğeri pisilife-2 den kurmak. 

steam kaynak kodu dağıtılmadığı için ana depolarımızda şu an yer alamıyor. o nedenle paket isteğini kapatmak durumundayız.
