### ISSUE TITLE
pisi ln hata veriyor.

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#573]
yeni paketleri görmek istediğimde hata veriyor.Bazı paketlerin metadata.xml dosyalarınnda yanlış tarihleme gördümdüzelttim ama olmuyor.
pisi ln -s 2015-08-21
Sistem hatası. Program sonlandırıldı.
time data '2012-20-21' does not match format '%Y-%m-%d'

**Comment by aydemir** [comment]
https://github.com/pisilinux/core/commit/4bcbcf0d11f13733a9e5b658fad9262f3a674640
http://ciftlik.pisilinux.org/pisi-2.0/f/fuse/
fuse paketinin release 4 olanlarını depodan elle silip index atalım
http://ciftlik.pisilinux.org/pisi-2.0/f/fuse/fuse-2.9.3-4-p01-x86_64.pisi
http://ciftlik.pisilinux.org/pisi-2.0/f/fuse/fuse-devel-2.9.3-4-p01-x86_64.pisi

**Comment by ertugerata** [comment]
libical ve fuse yeniden derlendi.

**Comment by alick01** [comment]
Denedim.Çok güzel oldu mükemmel çalışıyor. Bence kapanabilir.

**Comment by ertugerata** [comment]
teşekkürler
