### ISSUE TITLE
Format Kalıbının Güncellenmesi

### ISSUE THREAD

**Issue by FreeVirtualWorld** [pisilinux/main#5790]
Merhaba gençler, eminim ki bir çok linux dağıtımı gibi sizin de bir zaman çizergeniz, kendinize göre bir planınız vardır. Pisi Linux 2.0 Atatürk.iso kalıbının güncellenmesini tavsiye edecektim. Kalıp insanlığa sunalı yaklaşık 5 ay 1 hafta gibi bir süre geçmiş. Pisi Linux 2.0 kurulum yaptıktan sonra  500MB lık güncelleme indiriyor ve kurulumdan sonra bu güncelleme diskte 2GB gibi bir alan kaplıyor.
Bütün bu güncellemeleri kapsayacak şekil de yeni bir iso kalıbını oluşturulması faydalı olacaktır.

**Comment by ertugerata** [comment]
yayınlandı
