### ISSUE TITLE
user-manager

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#591]
user manager ile hem arayüzden hemde konsole ile yeni kullanıcı ekleyebiliyorum hata vermiyor ancak kullanıcılara giriş yapamıyorum.

**Comment by ertugerata** [comment]
add accountsservice dep.

**Comment by ertugerata** [comment]
Son durumu test eder misiniz. Bende kullanici ekleme tamam. Silme yok. O kullaniciyla giris yapamadim.

**Comment by alick01** [comment]
güncellemeden sonra ilk kullanıcı hariç diğerlerini sildim yeni kullanıcı oluşturdum ve giriş yaptımmmmmmm. Bence kapanabilir.

**Comment by ertugerata** [comment]
thanks @alick01 @alihanozturk
