### ISSUE TITLE
kexi dosya okuma hatası

### ISSUE THREAD

**Issue by suvari** [pisilinux/main#5927]
Qt WebEngine seems to be initialized from a plugin. Please set Qt::AA_ShareOpenGLContexts using QCoreApplication::setAttribute before constructing QGuiApplication.
kf5.kservice.sycoca: Parse error in  "/home/test/.config/menus/applications-merged/xdg-desktop-menu-dummy.menu" , line  1 , col  1 :  "unexpected end of file"
kf5.kservice.services: The desktop file "/usr/share/applications/sublime_text.desktop" references the action "Window" but doesn't define it
kf5.kservice.services: The desktop file "/usr/share/applications/sublime_text.desktop" references the action "Document" but doesn't define it
kf5.kservice.services: The desktop entry file "/usr/share/applications/org.kde.drkonqi.desktop" has Type= "Application" but no Exec line
kf5.kservice.sycoca: Invalid Service :  "/usr/share/applications/org.kde.drkonqi.desktop"
kf5.kservice.services: The desktop entry file "/usr/share/applications/org.kde.systemmonitor.desktop" has Type= "Application" but no Exec line
kf5.kservice.sycoca: Invalid Service :  "/usr/share/applications/org.kde.systemmonitor.desktop"
kf5.kservice.services: The desktop file "/home/test/.local/share/applications/sublime_text.desktop" references the action "Window" but doesn't define it
kf5.kservice.services: The desktop file "/home/test/.local/share/applications/sublime_text.desktop" references the action "Document" but doesn't define it
kf5.kio.core: Invalid URL: QUrl("")
Error while receiving .list file - no files will be updated
"kfiledialog"
("application/vnd.ms-access", "text/tab-separated-values")
("application/vnd.ms-access", "text/tab-separated-values")
("application/vnd.ms-access", "text/tab-separated-values")
org.kde.kdb.mysqldriver:
org.kde.kdb.mysqldriver:
NOTICE:  extension "fuzzystrmatch" already exists, skipping
NOTICE:  extension "fuzzystrmatch" already exists, skipping
org.kde.kdb.core: !querySingleStringInternal() KDbEscapedString:"SELECT db_value FROM kexi__db WHERE db_property='kexidb_major_ver' LIMIT 1"
!d->connection->useDatabase()  "pisi"   "org.kde.kdb.postgresql"
QXcbConnection: XCB error: 3 (BadWindow), sequence: 35197, resource id: 39853026, major code: 40 (TranslateCoords), minor code: 0

**Comment by ertugerata** [comment]
bu hata ile ilgili durum nedir @suvari

**Comment by suvari** [comment]
fixed
