### ISSUE TITLE
kdemenu sorunu

### ISSUE THREAD

**Issue by erkanisik1** [pisilinux/main#6110]
pisi menu kurulu olan programları göstermiyor örneğin qbittorent kurulu olmasına rağmen menüde gözükmüyor ve aramalarda da çıkmıyor konsoldan yazınca çalışıyor,uygulamaya sağ tıklayıp gelen pencerede uygulamalar kısmındayken tamam demekte çözüm olmadı gelmedi uygulamalar

**Comment by suvari** [comment]
Düzeltildi.
