### ISSUE TITLE
kcoreaddons-devel yapılandırması başarısız..

### ISSUE THREAD

**Issue by suvari** [pisilinux/main#615]
kcoreaddons-devel-5.14.0-4-p01-x86_64.pisi [önbellekte]
kcoreaddons-devel paketi 5.14.0 sürümü 4 yayımı kuruluyor
kcoreaddons-devel dosyaları arşivden çıkartılıyor.
files.xml depolanıyor.
metadata.xml depolanıyor.
comar/package.py depolanıyor.
kcoreaddons-devel paketi yapılandırılıyor
DEBUG: comar betiği System.Package kayıt ediliyor
DEBUG: Kurulum sonrası betikleri çağrılıyor
DEBUG: Paketin kurulum sonrası betiği çağrılıyor
kcoreaddons-devel yapılandırması başarısız oldu.
kcoreaddons-devel kuruldu.

**Comment by ertugerata** [comment]
kcoreaddons yapılandırması docker içinde paket inşa aşamasında yapılamıyor.

**Comment by ertugerata** [comment]
kcoreaddons yapılandırması docker içinde paket inşa  aşamasında yapılamıyor.

**Comment by ertugerata** [comment]
https://github.com/pisilinux/main/commit/5814a063e8f51ea0075ebf8758b5ad437e2a3bfb fix this issue
