### ISSUE TITLE
Bir yıldan beri ellenmemiş paketleri kontrol edilmeli

### ISSUE THREAD

**Issue by ertugerata** [pisilinux/main#6811]
- [x] 2018-02-22 /util/crypt/crypto++/pspec.xml
- [x] 2018-01-16 /office/spellcheck/qtspell/pspec.xml
- [x] 2018-03-23 /office/spellcheck/zemberek-office/pspec.xml
- [x] 2016-06-09 /hardware/disk/xfsprogs/pspec.xml
- [x] 2017-02-09 /server/database/sqlcipher/pspec.xml
- [x] 2017-01-28 /network/mail/sylpheed/pspec.xml
- [x] 2017-02-18 /network/connection/linux-atm/pspec.xml
- [x] 2017-07-30 /network/web/lynx/pspec.xml
- [x] 2017-07-30 /network/chat/pidgin/pspec.xml
- [x] 2017-04-29 /multimedia/sound/knowthelist/pspec.xml
- [x] 2017-04-24 /multimedia/graphics/gimp/addon/gimp-dds-plugin/pspec.xml
- [x] 2017-04-24 /multimedia/graphics/gimp/addon/colorize-gimp/pspec.xml
- [x] 2017-04-24 /multimedia/graphics/gimp/addon/gimpfx-foundry/pspec.xml
- [x] 2017-04-24 /multimedia/graphics/gimp/addon/gimp-lqr-plugin/pspec.xml
- [x] 2017-04-24 /multimedia/graphics/gimp/addon/gimp-focusblur-plugin/pspec.xml
- [x] 2017-04-24 /multimedia/graphics/gimp/addon/gimp-save-for-web/pspec.xml
- [x] 2017-04-24 /multimedia/graphics/gimp/addon/gimp-refocus-it-plugin/pspec.xml
- [x] 2017-04-24 /multimedia/graphics/gimp/addon/gimp-data-extras/pspec.xml
- [x] 2017-04-24 /multimedia/graphics/gimp/addon/gimp-layer-effects/pspec.xml
- [x] 2017-04-24 /multimedia/graphics/gimp/addon/gimp-resynthesizer/pspec.xml
- [ ] 2017-03-19 /desktop/toolkit/qt5/qt5-quick1/pspec.xml
- [x] 2018-01-02 /desktop/gnome/base/gvfs/pspec.xml
- [x] 2017-05-28 /desktop/pisilinux/pisiplayer/pspec.xml
- [ ] 2016-03-06 /kernel/drivers/module-fglrx/pspec.xml
- [x] 2018-02-20 /programming/scm/libgit2/pspec.xml
- [x] 2017-06-09 /programming/misc/libnice/pspec.xml
- [x] 2018-01-31 /programming/language/python3/py3parted/pspec.xml

**Comment by ertugerata** [comment]
@Rmys abi qt5-quick1 i atıyor muyuz

**Comment by suvari** [comment]
fixed
