### ISSUE TITLE
akonadi servis çalışmıyor.

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#695]
akonadi paketi yüklü olmasına rağmen servis listesinde görünmüyor.Servis başlatılmadığı için kmail, korganizer ve kontact çalışmıyor.

**Comment by aydemir** [comment]
<Dependency>mariadb-client</Dependency>
<Dependency>mariadb-server</Dependency>

**Comment by aydemir** [comment]
postersql

**Comment by aydemir** [comment]
shared-mime-info-1.4, libxslt-1.1.28, Boost-1.59.0, and one of: SQLite-3.9.1, MariaDB-10.1.8, MySQL, or PostgreSQL-9.4.4

**Comment by ertugerata** [comment]
Eksik bagimliliktan ziyade dbus servislerinin duzgun baslatilamamasi ile bir sorun var tahminimce. Konsolda servisin baslayip baslamadigini test etmek gerekiyor

**Comment by alick01** [comment]
Konsolda service list istediğimde akonadi görünmüyor.service akonadi start dediğimde bulunamadı cevabı veriyor."Unable to find '/var/db/comar3/scripts/System.Service/akonadi.py'"

**Comment by ertugerata** [comment]
akonadi nin comar script i yok. 
çalışıp çalışmadığını
ps aux |grep akonadi ile bakabilirsiniz.

**Comment by alick01** [comment]
Ben yeniden yükledim 2.0 alpha6 güncelledim hala çalışmıyor kmail kontact korganizer.bütün servisler çalışıyor mariadb akonadi hala The Akonadi personal information management service is not operational diyor

**Comment by alick01** [comment]
kontact çalıştırınca ve akonadi self test raporunu ekledim
[akonadi-selftest-report-20151214.txt](https://github.com/pisilinux/main/files/65142/akonadi-selftest-report-20151214.txt)
[kontact.txt](https://github.com/pisilinux/main/files/65143/kontact.txt)

**Comment by ertugerata** [comment]
niye kapattın abi ?

**Comment by alihanozturk** [comment]
konsole service mariadb start komutunu verip
kmail vs. çalışıyormu tekrar denermisiniz acaba

**Comment by alick01** [comment]
ben mariadb-server i daha önce açılışta çalışacak şekilde ayarlamıştım.Ama sorun devam ediyor.akonadi serveri kapatınca kmail ve diğerleri hatasız açılıyor ama akonadiyi başlattığım zaman hataya geçiyor.Bende çok araştırıyorum ama ççare bulamadım.Sadece dikkatimi 1.2 ile 2.0 arasındaki fark çekti. 1.2 de akonadi_agent_launcher olarak 6 adet proses çalışıyor ve baloo_indexer var 2.0 da bunlar yok

**Comment by ertugerata** [comment]
akonadi-server i nasıl kapatıyorsun?

**Comment by alick01** [comment]
akonadictl ştop
Biraz önce kdepim-runtime paketini kurdum ve herşey çalışıyor.

**Comment by alick01** [comment]
Bu sabah tekrar kontrol ettim kdepim-runtime kaldırdım reboottan sonra aynı sorun oluştu.kdepim-runtime bağımlılıklara eklenmeli böylece hata kapanabilir.

**Comment by bferturk** [comment]
Problem tekrarlandı.


`log_kidentitymanagement: IdentityManager: There was no default identity. Marking first one as default.                                                        
Connecting to deprecated signal QDBusConnectionInterface::serviceOwnerChanged(QString,QString,QString)                                                        
QCommandLineParser: option not defined: "start-without-control"                                                                                               
akonadiprivate_log: search paths:  ("/usr/share/colorgcc", "/usr/local/bin", "/usr/local/sbin", "/usr/bin", "/usr/sbin", "/bin", "/sbin", "/opt/bin", "/usr/sbin", "/usr/local/sbin", "/usr/local/libexec", "/usr/libexec", "/opt/mysql/libexec", "/opt/local/lib/mysql5/bin", "/opt/mysql/sbin")                           
Found mysql_install_db:  "/usr/bin/mysql_install_db"                                                                                                          
Found mysqlcheck:  "/usr/bin/mysqlcheck"                                                                                                                      
akonadiserver: relocation error: /usr/lib/qt5/plugins/sqldrivers/libqsqlmysql.so: symbol mysql_server_init, version libmysqlclient_16 not defined in file libmysqlclient.so.18 with link time reference                                                                                                                     
ProcessControl: Application 'akonadiserver' returned with exit code 127 (Unknown error)                                                                       
QCommandLineParser: option not defined: "start-without-control"
akonadiprivate_log: search paths:  ("/usr/share/colorgcc", "/usr/local/bin", "/usr/local/sbin", "/usr/bin", "/usr/sbin", "/bin", "/sbin", "/opt/bin", "/usr/sbin", "/usr/local/sbin", "/usr/local/libexec", "/usr/libexec", "/opt/mysql/libexec", "/opt/local/lib/mysql5/bin", "/opt/mysql/sbin")
Found mysql_install_db:  "/usr/bin/mysql_install_db"
Found mysqlcheck:  "/usr/bin/mysqlcheck"
akonadiserver: relocation error: /usr/lib/qt5/plugins/sqldrivers/libqsqlmysql.so: symbol mysql_server_init, version libmysqlclient_16 not defined in file libmysqlclient.so.18 with link time reference
ProcessControl: Application 'akonadiserver' returned with exit code 127 (Unknown error)
QCommandLineParser: option not defined: "start-without-control"
akonadiprivate_log: search paths:  ("/usr/share/colorgcc", "/usr/local/bin", "/usr/local/sbin", "/usr/bin", "/usr/sbin", "/bin", "/sbin", "/opt/bin", "/usr/sbin", "/usr/local/sbin", "/usr/local/libexec", "/usr/libexec", "/opt/mysql/libexec", "/opt/local/lib/mysql5/bin", "/opt/mysql/sbin")
Found mysql_install_db:  "/usr/bin/mysql_install_db"
Found mysqlcheck:  "/usr/bin/mysqlcheck"
log_messageviewer: No plugin found !
log_messageviewer: No plugin found !
akonadiserver: relocation error: /usr/lib/qt5/plugins/sqldrivers/libqsqlmysql.so: symbol mysql_server_init, version libmysqlclient_16 not defined in file libmysqlclient.so.18 with link time reference
ProcessControl: Application 'akonadiserver' returned with exit code 127 (Unknown error)
QCommandLineParser: option not defined: "start-without-control"
akonadiprivate_log: search paths:  ("/usr/share/colorgcc", "/usr/local/bin", "/usr/local/sbin", "/usr/bin", "/usr/sbin", "/bin", "/sbin", "/opt/bin", "/usr/sbin", "/usr/local/sbin", "/usr/local/libexec", "/usr/libexec", "/opt/mysql/libexec", "/opt/local/lib/mysql5/bin", "/opt/mysql/sbin")
Found mysql_install_db:  "/usr/bin/mysql_install_db"
Found mysqlcheck:  "/usr/bin/mysqlcheck"
akonadiserver: relocation error: /usr/lib/qt5/plugins/sqldrivers/libqsqlmysql.so: symbol mysql_server_init, version libmysqlclient_16 not defined in file libmysqlclient.so.18 with link time reference
ProcessControl: Application 'akonadiserver' returned with exit code 127 (Unknown error)
"akonadiserver" crashed too often and will not be restarted!
log_messageviewer: No plugin found !
this does not work on a KActionCollection containing actions!
akonadicore_log: Socket error occurred: "QLocalSocket::connectToServer: Invalid name"
akonadicore_log: Socket error occurred: "QLocalSocket::connectToServer: Invalid name"
org.kde.akonadi.ETM: GEN true false false
org.kde.akonadi.ETM: collection: QVector()
org.kde.akonadi.ETM: 
akonadicore_log: Job error:  "Unknown error." for collection: QVector() 

akonadicore_log: Job error:  "Unknown error." for collection: QVector() 

log_messagelist: Failed to load tags  "Unknown error."
log_mailcommon: failed to retrieve tags  "Unknown error."
log_kmail: "Unknown error."
`

**Comment by bferturk** [comment]
problem binutilse doğru gidiyor.

https://kaosx.us/phpBB3/viewtopic.php?t=1375

http://www.linuxquestions.org/questions/slackware-14/current-akonadi-mariadb-mysql-and-kmail-4175574130/

**Comment by suvari** [comment]
fixed..
