### ISSUE TITLE
kanagram

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#719]
kanagram kurdum.Konsole ile çalıştırdım sadece beyaz bir pencere açıldı ve çalışmadı.
Hata mesajında qt-multimedia bulunamadı yazıyordu. Sistemimde kurulu değilmiş kurdum kanagramhatasız çalıştı. Runtime bağımlılıklarında qt5-multimedia yok eklenmesi gerekir.

**Comment by alick01** [comment]
Bende çalışıyor kapanabilir

**Comment by ertugerata** [comment]
eklenmiş mi bağımlılık ?

**Comment by alick01** [comment]
3 ocakta güncelleme gelmiş ama bağımlılık eklenmemiş bende çalışınca tamamdır farzettim.demek ki bakmak gerekiyormuş.eklenmemiş ve qt5-multimedia yı kaldırınca hata verdi çalışmadı.
kanagram(1072)/default unknown: file:///usr/share/kanagram/ui/main.qml:23:1: module "QtMultimedia" is not installed 
     import QtMultimedia 5.0

**Comment by alihanozturk** [comment]
qt5-multimedia eklendi kapatılabilir

**Comment by ertugerata** [comment]
bağımlılık eklendi. paket depoda @alick01 dener misiniz.
