### ISSUE TITLE
öntanımlı dosya yöneticisi

### ISSUE THREAD

**Issue by suvari** [pisilinux/main#723]
http://i.hizliresim.com/jjNWEJ.jpg
Konqueror yerine dolphin olsa..

**Comment by ertugerata** [comment]
buna ait yapılandırma dosyasını önceden ayarlayabiliyor muyuz?

**Comment by MuhammetDilmac** [comment]
Sanırım dosyamız burada
```
/usr/share/applications/defaults.list
```

**Comment by ertugerata** [comment]
shared-mime-info dosyası içerisinde
