### ISSUE TITLE
Update audacity to 2.3.3

### ISSUE THREAD

**Issue by luzpaz** [pisilinux/main#7321]
https://www.audacityteam.org/audacity-2-3-3-released/  
https://github.com/audacity/audacity/releases/tag/Audacity-2.3.3

**Comment by blue-devil** [comment]
upgraded to latest release
https://github.com/pisilinux/main/pull/8546/commits/92b3503cabe7e220eeb60c29e564ebf4112da005

**Comment by luzpaz** [comment]
@blue-devil couldn't tell from the commit, but 2.4.1 is latest release. See https://www.audacityteam.org/audacity-2-4-1-released/

**Comment by blue-devil** [comment]
@luzpaz https://github.com/pisilinux/main/pull/8556/commits/681fd01a52340a63ec91f06479d903a48474b998
updated
