### ISSUE TITLE
hugin exiv2 güncellemesi nedeni ile kırık

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#735]
bugünkü exiv2-libs güncellemesinden sonra gwenview açılmıyor.Hata;
gwenview: error while loading shared libraries: libexiv2.so.13: cannot open shared object file: No such file or directory

**Comment by ertugerata** [comment]
revdep-rebuild -f

Collecting installed packages and files...
  done.

Collecting old paths info...
  done.

Checking reverse dependencies...

Collecting system binaries and libraries...
  done. (/root/.revdep-rebuild.1_files)

Collecting complete LD_LIBRARY_PATH...
  done. (/root/.revdep-rebuild.2_ldpath)

Checking dynamic linking consistency...
  broken /usr/bin/gwenview requires libexiv2.so.13
  broken /usr/lib/libgwenviewlib.so.4.97.0 requires libexiv2.so.13
  broken /usr/lib/qt5/plugins/gvpart.so requires libexiv2.so.13
  broken /usr/lib/qt5/plugins/jpegthumbnail.so requires libexiv2.so.13
  broken /usr/lib/qt5/plugins/kf5/kfilemetadata/kfilemetadata_exiv2extractor.so requires libexiv2.so.13
  done. (/root/.revdep-rebuild.3_rebuild)

Determining package names consistency...
  kfilemetadata has /usr/lib/qt5/plugins/kf5/kfilemetadata/kfilemetadata_exiv2extractor.so and it needs libexiv2.so.13 from exiv2-libs
  kio-extras has /usr/lib/qt5/plugins/jpegthumbnail.so and it needs libexiv2.so.13 from exiv2-libs
  gwenview has /usr/bin/gwenview and it needs libexiv2.so.13 from exiv2-libs
  gwenview has /usr/lib/libgwenviewlib.so.4.97.0 and it needs libexiv2.so.13 from exiv2-libs
  gwenview has /usr/lib/qt5/plugins/gvpart.so and it needs libexiv2.so.13 from exiv2-libs
  done. (/root/.revdep-rebuild.4_lnames, /root/.revdep-rebuild.4_rdnames)

**Comment by alick01** [comment]
Hata giderildi Kapanabilir.

**Comment by ertugerata** [comment]
hugin kaldı.
