### ISSUE TITLE
libdrm

### ISSUE THREAD

**Issue by suvari** [pisilinux/main#803]
https://github.com/pisilinux/main/blob/master/x11/library/libdrm/pspec.xml
releaseFrom hataları var, 32 bit olanlara da bakılmalı (<Dependency releaseFrom="2">libpciaccess-32bit</Dependency>),
versionFrom olacak sanırım, 
karşılanmamış bağımlılık olarak gözüken libpciaccess: https://github.com/pisilinux/main/blob/master/x11/library/libpciaccess/pspec.xml    libdrm, buradaki releaseFrom 2 ye yönlenmiş

**Comment by ertugerata** [comment]
fix with  https://github.com/pisilinux/main/commit/107a2cf71892a32df50d85c9024c3d721f7af87f
