### ISSUE TITLE
"tvtime veya xawtv" tv programı olarak depoya alınması

### ISSUE THREAD

**Issue by slarikan** [pisilinux/main#810]
akşamları tv seyrederken bi taraftanta gonullu çalıştırmak isitiyorum ama depoda hiç tv programı yok (tercihen)tvtime veya xawtv enazından biri depoya alınırsa memnun olurum

**Comment by ertugerata** [comment]
kaynak depoya alındı derlenmesi bekleniyor

**Comment by ertugerata** [comment]
paket depoda; bu paket ile ilgili kullanım hatalarını yeni issue ye girer misiniz @slarikan 

pisi info xawtv
Paket pisi deposunda bulundu:
İsim                : xawtv, sürüm: 3.103, yayım: 4
Özet                : TV uygulaması
Açıklama            : xawtv Xvideo, v4l2, bktr gibi birçok arayüzü destekleyen bir TV uygulamasıdır. xawtv ayrıca video kayıt yeteneği ve birkaç yararlı konsol aracına sahiptir.
Lisanslar           : GPLv2
Bileşen             : multimedia.tv
Sağladıkları        : 
Bağımlılıkları      : zvbi lirc mesa aalib libSM libdv libXt libXv libXmu libXaw libICE libv4l libXpm libXft libXext alsa-lib libXrandr libXrender libXxf86vm fontconfig libexplain
                      libXxf86dga libXinerama libquicktime libjpeg-turbo gpm zlib libX11 libpng ncurses freetype 
Dağıtım             : PisiLinux, Dağıtım Sürümü: 1.0
Mimari              : x86_64, Yerleşik Boyut: 2.07 MB, Paket Boyutu: 395.00 KB, install.tar.xz sha1sum: 20f5591af1a78eccb7c07b16b20d7751b4355583
