### ISSUE TITLE
dolphin "yeni dizin oluştur" da çöküyor.

### ISSUE THREAD

**Issue by ertugerata** [pisilinux/main#853]
ev dizini aç 
sağ click 
create new -- yeni dizin

dolphin çöküyor. 

![snapshot1_1024](https://cloud.githubusercontent.com/assets/225387/11263756/633f0dee-8e96-11e5-9469-2f082fa486b3.png)

**Comment by alihanozturk** [comment]
https://ask.fedoraproject.org/en/question/43027/both-kde-file-managers-dolphin-and-konqueror-are-crashing/

abi yanlış olmasın Yeni Klasör de değil

New-->Folder yaptınmı sıkıntı yok
New-->Dizin dersen sıkıntı var

**Comment by alihanozturk** [comment]
Bu hatanın sebebi drkonqi paketine <Path fileType="executable">/usr/lib/libexec</Path>  bu şekilde bir path yolu verildiği için olabilir.

ve birde kcrash paketine dronki yazılmalı mı?

drkonqi paketine gdb dep olmalımı ?
