### ISSUE TITLE
Yeni dizin açınca plasma çökmesi

### ISSUE THREAD

**Issue by alihanozturk** [pisilinux/main#859]
Masaüstünde veya herhangi bir yerde

Sağ Tık-->Yeni Oluştur(Create New)-->Dizin 

dediğimizde Plasma Çöktü Uyarısı veriyor

**Comment by ertugerata** [comment]
https://github.com/pisilinux/main/issues/853 ile aynı hata...

**Comment by alihanozturk** [comment]
o zaman diğer hatanın başlığını değiştir abi Yeni Klasör değil Yeni Dizin oluştur dediğinde alıyorsun bu hatayı. yanlış şeyler peşinde koşmayalım
