### ISSUE TITLE
Solved issues.

### ISSUE THREAD

**Issue by 4fury-c3440d8** [pisilinux/main#8716]
Please, close this issues:
- 7460, krita-4.3.0
- 7340, darktable-3.0.1
- 7032, blender-2.83
- 6959, hunspell-1.7.0
- 6135, opencv-4.2.0
- 6133, fftw-3.3.8
- 4896, wxGTK3
- 4793, 4794, package-manager

and some obsolete.

**Comment by blue-devil** [comment]
Solved issues closed
