### ISSUE TITLE
kde kurarken dosya çakışması kio paketi

### ISSUE THREAD

**Issue by milisarge** [pisilinux/main#886]
Kuruluyor 189 / 208
kio-5.16.0-6-p01-x86_64.pisi [önbellekte]
kio paketi 5.16.0 sürümü 6 yayımı kuruluyor
Program sonlandırıldı.
Dosya çakışmaları:
/usr/share/kservicetypes5/konqpopupmenuplugin.desktop kde-baseapps paketinden

**Comment by ertugerata** [comment]
yeni kde-baseapps ile çözüldü
