### ISSUE TITLE
Dosya paylaşımları

### ISSUE THREAD

**Issue by alick01** [pisilinux/main#915]
2.0 kullanıyorum.Samba servisi var ama sistem ayarlarında paylaşım görünmüyor. Dolphinde dizin ve dosya özelliklerinde paylaştır seçeneği de yok.1.2 de smb4k isimli bir paket var bu 2.0 da yok.

**Comment by alick01** [comment]
Smb4K 2.0.0 released
by Alexander Reinholdt 2017-03-11
The Smb4K team is proud to announce the immediate availability of Smb4K 2.0.0, the first Qt5 and KF5 based version of Smb4K.
Changes since Smb4K 1.2 can be viewed in the Git log, the source can be downloaded from our download section.

**Comment by alick01** [comment]
goni make smb4k package and I install smb4k running but I didn't test it because I have no workgroup.

**Comment by groni** [comment]
No problem, it works i have test smb4k it works fine
