### ISSUE TITLE
çakışmalar / conflicts..

### ISSUE THREAD

**Issue by suvari** [pisilinux/main#943]
11 aralık 2015 itibariyle,
 depo güncellenirken bazı çakışmalar oluyor: 
https://paste.kde.org/pptislk8n
​
https://paste.kde.org/p7apsqdhr

https://paste.kde.org/pxzh7ylvz

https://paste.kde.org/pbh8nyxww

**Comment by ertugerata** [comment]
kscreenlocker plasma-desktop içerisinden ayrıldığı için bu hata normal.
