### ISSUE TITLE
qt5-declarative problem with the xmllistmodel

### ISSUE THREAD

**Issue by groni** [pisilinux/main#983]
Hi
It gives a problem with the qt5-declarative package few applications gives this error "Error loading QML file: file:///home/groni/.local5/share/plasma/plasmoids/org.kde.weatherWidget/contents/ui/main.qml:21:1: module "QtQuick.XmlListModel" is not installed"
in Arch Linux is the Package available look here:
![qml](https://cloud.githubusercontent.com/assets/3329657/11918010/5e4e1c8e-a71f-11e5-848d-6bc720d495c8.png)

**Comment by ertugerata** [comment]
it's OK ? @groni

**Comment by groni** [comment]
Yes it is ok 
No problem with the widgets all is OK
