### ISSUE TITLE
PPtp ile VPN bağlantısı hatası

### ISSUE THREAD

**Issue by drmst** [pisilinux/main#9832]
PPTP protokolu ile vpn  bağlantısı kurmaya çalıştığımda "eksik VPN eklentisi" hatası çıkıyor. Başka dağıtımlar için önerilen "network-manager-openvpn" paketini depoda bulamadığım için bunun yerine "openvpn"paketini kurdum ama halen aynı hatayı veriyor. Teşekkürler

**Comment by suvari** [comment]
networkmanager-openvpn depoya alındı.
