### ISSUE TITLE
KRunner çalışmıyor

### ISSUE THREAD

**Issue by drmst** [pisilinux/main#9833]
KDE'de Alt+F2 veya Alt+Boşluk tuşlarına basınca çalışan ekranın üst kısmında gözüken Krunner çalışmıyor. Krunner'ın olması gerektiği yerde temadan temaya değişmek üzere siyah bir nokta yada silik bir iz gözüküyor. Sorun kısa yolun kendisi ile ilgili değil. Masüstünde sağ tık> Krunner ı göstere tıklayıncada aynı şey oluyor. Teşekkürler

**Comment by suvari** [comment]
Düzeltildi.
